// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	verifyCodeFieldNames          = builder.RawFieldNames(&VerifyCode{})
	verifyCodeRows                = strings.Join(verifyCodeFieldNames, ",")
	verifyCodeRowsExpectAutoSet   = strings.Join(stringx.Remove(verifyCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	verifyCodeRowsWithPlaceHolder = strings.Join(stringx.Remove(verifyCodeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheVerifyCodeIdPrefix = "cache:verifyCode:id:"
)

type (
	verifyCodeModel interface {
		Insert(ctx context.Context, data *VerifyCode) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VerifyCode, error)
		Update(ctx context.Context, data *VerifyCode) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVerifyCodeModel struct {
		sqlc.CachedConn
		table string
	}

	VerifyCode struct {
		Id        int64     `db:"id"`
		Phone     string    `db:"phone"`      // 手机号
		Code      string    `db:"code"`       // 验证码
		Type      int64     `db:"type"`       // 类型 1:注册 2:登录 3:重置密码
		Status    int64     `db:"status"`     // 状态 0:未使用 1:已使用
		ExpireAt  time.Time `db:"expire_at"`  // 过期时间
		CreatedAt time.Time `db:"created_at"` // 创建时间
	}
)

func newVerifyCodeModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultVerifyCodeModel {
	return &defaultVerifyCodeModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`verify_code`",
	}
}

func (m *defaultVerifyCodeModel) Delete(ctx context.Context, id int64) error {
	verifyCodeIdKey := fmt.Sprintf("%s%v", cacheVerifyCodeIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, verifyCodeIdKey)
	return err
}

func (m *defaultVerifyCodeModel) FindOne(ctx context.Context, id int64) (*VerifyCode, error) {
	verifyCodeIdKey := fmt.Sprintf("%s%v", cacheVerifyCodeIdPrefix, id)
	var resp VerifyCode
	err := m.QueryRowCtx(ctx, &resp, verifyCodeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", verifyCodeRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVerifyCodeModel) Insert(ctx context.Context, data *VerifyCode) (sql.Result, error) {
	verifyCodeIdKey := fmt.Sprintf("%s%v", cacheVerifyCodeIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, verifyCodeRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Phone, data.Code, data.Type, data.Status, data.ExpireAt)
	}, verifyCodeIdKey)
	return ret, err
}

func (m *defaultVerifyCodeModel) Update(ctx context.Context, data *VerifyCode) error {
	verifyCodeIdKey := fmt.Sprintf("%s%v", cacheVerifyCodeIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, verifyCodeRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Phone, data.Code, data.Type, data.Status, data.ExpireAt, data.Id)
	}, verifyCodeIdKey)
	return err
}

func (m *defaultVerifyCodeModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheVerifyCodeIdPrefix, primary)
}

func (m *defaultVerifyCodeModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", verifyCodeRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultVerifyCodeModel) tableName() string {
	return m.table
}
