// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/media/media.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 上传元数据（streaming 首包）
type UploadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Quality       int32                  `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"` // 图片压缩质量 1-100，视频忽略此字段
	MaxWidth      int32                  `protobuf:"varint,4,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	MaxHeight     int32                  `protobuf:"varint,5,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMeta) Reset() {
	*x = UploadMeta{}
	mi := &file_proto_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMeta) ProtoMessage() {}

func (x *UploadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMeta.ProtoReflect.Descriptor instead.
func (*UploadMeta) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMeta) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadMeta) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *UploadMeta) GetMaxWidth() int32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

func (x *UploadMeta) GetMaxHeight() int32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

// 上传图片请求（streaming）
type UploadImageReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadImageReq_Meta
	//	*UploadImageReq_Chunk
	Data          isUploadImageReq_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageReq) Reset() {
	*x = UploadImageReq{}
	mi := &file_proto_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq) ProtoMessage() {}

func (x *UploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq.ProtoReflect.Descriptor instead.
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageReq) GetData() isUploadImageReq_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageReq) GetMeta() *UploadMeta {
	if x != nil {
		if x, ok := x.Data.(*UploadImageReq_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadImageReq) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadImageReq_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadImageReq_Data interface {
	isUploadImageReq_Data()
}

type UploadImageReq_Meta struct {
	Meta *UploadMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"` // 首包：元数据
}

type UploadImageReq_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // 后续包：分块数据
}

func (*UploadImageReq_Meta) isUploadImageReq_Data() {}

func (*UploadImageReq_Chunk) isUploadImageReq_Data() {}

// 上传视频请求（streaming）
type UploadVideoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadVideoReq_Meta
	//	*UploadVideoReq_Chunk
	Data          isUploadVideoReq_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoReq) Reset() {
	*x = UploadVideoReq{}
	mi := &file_proto_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoReq) ProtoMessage() {}

func (x *UploadVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoReq.ProtoReflect.Descriptor instead.
func (*UploadVideoReq) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoReq) GetData() isUploadVideoReq_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadVideoReq) GetMeta() *UploadMeta {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoReq_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *UploadVideoReq) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoReq_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadVideoReq_Data interface {
	isUploadVideoReq_Data()
}

type UploadVideoReq_Meta struct {
	Meta *UploadMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"` // 首包：元数据
}

type UploadVideoReq_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // 后续包：分块数据
}

func (*UploadVideoReq_Meta) isUploadVideoReq_Data() {}

func (*UploadVideoReq_Chunk) isUploadVideoReq_Data() {}

// 媒体信息
type MediaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Width         int32                  `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	Duration      int32                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"` // 视频时长（秒）
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix 时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaInfo) Reset() {
	*x = MediaInfo{}
	mi := &file_proto_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaInfo) ProtoMessage() {}

func (x *MediaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaInfo.ProtoReflect.Descriptor instead.
func (*MediaInfo) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *MediaInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MediaInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *MediaInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaInfo) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *MediaInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MediaInfo) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaInfo) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaInfo) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MediaInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MediaInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 上传图片响应
type UploadImageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResp) Reset() {
	*x = UploadImageResp{}
	mi := &file_proto_media_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResp) ProtoMessage() {}

func (x *UploadImageResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResp.ProtoReflect.Descriptor instead.
func (*UploadImageResp) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{4}
}

func (x *UploadImageResp) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// 上传视频响应
type UploadVideoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResp) Reset() {
	*x = UploadVideoResp{}
	mi := &file_proto_media_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResp) ProtoMessage() {}

func (x *UploadVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResp.ProtoReflect.Descriptor instead.
func (*UploadVideoResp) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{5}
}

func (x *UploadVideoResp) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// 获取媒体信息请求
type GetMediaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaReq) Reset() {
	*x = GetMediaReq{}
	mi := &file_proto_media_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaReq) ProtoMessage() {}

func (x *GetMediaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaReq.ProtoReflect.Descriptor instead.
func (*GetMediaReq) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaReq) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

// 获取媒体信息响应
type GetMediaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *MediaInfo             `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResp) Reset() {
	*x = GetMediaResp{}
	mi := &file_proto_media_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResp) ProtoMessage() {}

func (x *GetMediaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResp.ProtoReflect.Descriptor instead.
func (*GetMediaResp) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetMediaResp) GetMedia() *MediaInfo {
	if x != nil {
		return x.Media
	}
	return nil
}

// 删除媒体请求
type DeleteMediaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaReq) Reset() {
	*x = DeleteMediaReq{}
	mi := &file_proto_media_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaReq) ProtoMessage() {}

func (x *DeleteMediaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaReq.ProtoReflect.Descriptor instead.
func (*DeleteMediaReq) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMediaReq) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *DeleteMediaReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 删除媒体响应
type DeleteMediaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResp) Reset() {
	*x = DeleteMediaResp{}
	mi := &file_proto_media_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResp) ProtoMessage() {}

func (x *DeleteMediaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResp.ProtoReflect.Descriptor instead.
func (*DeleteMediaResp) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{9}
}

// 批量获取媒体信息请求
type BatchGetMediaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaIds      []int64                `protobuf:"varint,1,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMediaReq) Reset() {
	*x = BatchGetMediaReq{}
	mi := &file_proto_media_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMediaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMediaReq) ProtoMessage() {}

func (x *BatchGetMediaReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMediaReq.ProtoReflect.Descriptor instead.
func (*BatchGetMediaReq) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetMediaReq) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

// 批量获取媒体信息响应
type BatchGetMediaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*MediaInfo           `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetMediaResp) Reset() {
	*x = BatchGetMediaResp{}
	mi := &file_proto_media_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMediaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMediaResp) ProtoMessage() {}

func (x *BatchGetMediaResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_media_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMediaResp.ProtoReflect.Descriptor instead.
func (*BatchGetMediaResp) Descriptor() ([]byte, []int) {
	return file_proto_media_media_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetMediaResp) GetMedias() []*MediaInfo {
	if x != nil {
		return x.Medias
	}
	return nil
}

var File_proto_media_media_proto protoreflect.FileDescriptor

const file_proto_media_media_proto_rawDesc = "" +
	"\n" +
	"\x17proto/media/media.proto\x12\x05media\"\x98\x01\n" +
	"\n" +
	"UploadMeta\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x18\n" +
	"\aquality\x18\x03 \x01(\x05R\aquality\x12\x1b\n" +
	"\tmax_width\x18\x04 \x01(\x05R\bmaxWidth\x12\x1d\n" +
	"\n" +
	"max_height\x18\x05 \x01(\x05R\tmaxHeight\"Y\n" +
	"\x0eUploadImageReq\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.media.UploadMetaH\x00R\x04meta\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"Y\n" +
	"\x0eUploadVideoReq\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x11.media.UploadMetaH\x00R\x04meta\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"\xc3\x02\n" +
	"\tMediaInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x14\n" +
	"\x05width\x18\b \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\t \x01(\x05R\x06height\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\"9\n" +
	"\x0fUploadImageResp\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaInfoR\x05media\"9\n" +
	"\x0fUploadVideoResp\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaInfoR\x05media\"(\n" +
	"\vGetMediaReq\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\"6\n" +
	"\fGetMediaResp\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.media.MediaInfoR\x05media\"D\n" +
	"\x0eDeleteMediaReq\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x03R\amediaId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x11\n" +
	"\x0fDeleteMediaResp\"/\n" +
	"\x10BatchGetMediaReq\x12\x1b\n" +
	"\tmedia_ids\x18\x01 \x03(\x03R\bmediaIds\"=\n" +
	"\x11BatchGetMediaResp\x12(\n" +
	"\x06medias\x18\x01 \x03(\v2\x10.media.MediaInfoR\x06medias2\xc5\x02\n" +
	"\fMediaService\x12>\n" +
	"\vUploadImage\x12\x15.media.UploadImageReq\x1a\x16.media.UploadImageResp(\x01\x12>\n" +
	"\vUploadVideo\x12\x15.media.UploadVideoReq\x1a\x16.media.UploadVideoResp(\x01\x123\n" +
	"\bGetMedia\x12\x12.media.GetMediaReq\x1a\x13.media.GetMediaResp\x12<\n" +
	"\vDeleteMedia\x12\x15.media.DeleteMediaReq\x1a\x16.media.DeleteMediaResp\x12B\n" +
	"\rBatchGetMedia\x12\x17.media.BatchGetMediaReq\x1a\x18.media.BatchGetMediaRespB\x14Z\x12xiaobaihe/media/pbb\x06proto3"

var (
	file_proto_media_media_proto_rawDescOnce sync.Once
	file_proto_media_media_proto_rawDescData []byte
)

func file_proto_media_media_proto_rawDescGZIP() []byte {
	file_proto_media_media_proto_rawDescOnce.Do(func() {
		file_proto_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)))
	})
	return file_proto_media_media_proto_rawDescData
}

var file_proto_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_media_media_proto_goTypes = []any{
	(*UploadMeta)(nil),        // 0: media.UploadMeta
	(*UploadImageReq)(nil),    // 1: media.UploadImageReq
	(*UploadVideoReq)(nil),    // 2: media.UploadVideoReq
	(*MediaInfo)(nil),         // 3: media.MediaInfo
	(*UploadImageResp)(nil),   // 4: media.UploadImageResp
	(*UploadVideoResp)(nil),   // 5: media.UploadVideoResp
	(*GetMediaReq)(nil),       // 6: media.GetMediaReq
	(*GetMediaResp)(nil),      // 7: media.GetMediaResp
	(*DeleteMediaReq)(nil),    // 8: media.DeleteMediaReq
	(*DeleteMediaResp)(nil),   // 9: media.DeleteMediaResp
	(*BatchGetMediaReq)(nil),  // 10: media.BatchGetMediaReq
	(*BatchGetMediaResp)(nil), // 11: media.BatchGetMediaResp
}
var file_proto_media_media_proto_depIdxs = []int32{
	0,  // 0: media.UploadImageReq.meta:type_name -> media.UploadMeta
	0,  // 1: media.UploadVideoReq.meta:type_name -> media.UploadMeta
	3,  // 2: media.UploadImageResp.media:type_name -> media.MediaInfo
	3,  // 3: media.UploadVideoResp.media:type_name -> media.MediaInfo
	3,  // 4: media.GetMediaResp.media:type_name -> media.MediaInfo
	3,  // 5: media.BatchGetMediaResp.medias:type_name -> media.MediaInfo
	1,  // 6: media.MediaService.UploadImage:input_type -> media.UploadImageReq
	2,  // 7: media.MediaService.UploadVideo:input_type -> media.UploadVideoReq
	6,  // 8: media.MediaService.GetMedia:input_type -> media.GetMediaReq
	8,  // 9: media.MediaService.DeleteMedia:input_type -> media.DeleteMediaReq
	10, // 10: media.MediaService.BatchGetMedia:input_type -> media.BatchGetMediaReq
	4,  // 11: media.MediaService.UploadImage:output_type -> media.UploadImageResp
	5,  // 12: media.MediaService.UploadVideo:output_type -> media.UploadVideoResp
	7,  // 13: media.MediaService.GetMedia:output_type -> media.GetMediaResp
	9,  // 14: media.MediaService.DeleteMedia:output_type -> media.DeleteMediaResp
	11, // 15: media.MediaService.BatchGetMedia:output_type -> media.BatchGetMediaResp
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_media_media_proto_init() }
func file_proto_media_media_proto_init() {
	if File_proto_media_media_proto != nil {
		return
	}
	file_proto_media_media_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadImageReq_Meta)(nil),
		(*UploadImageReq_Chunk)(nil),
	}
	file_proto_media_media_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadVideoReq_Meta)(nil),
		(*UploadVideoReq_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_media_media_proto_rawDesc), len(file_proto_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_media_media_proto_goTypes,
		DependencyIndexes: file_proto_media_media_proto_depIdxs,
		MessageInfos:      file_proto_media_media_proto_msgTypes,
	}.Build()
	File_proto_media_media_proto = out.File
	file_proto_media_media_proto_goTypes = nil
	file_proto_media_media_proto_depIdxs = nil
}
