// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: message.proto

package messageservice

import (
	"context"
	pb2 "esx/app/message/rpc/xiaobaihe/message/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConversationInfo     = pb2.ConversationInfo
	GetConversationsReq  = pb2.GetConversationsReq
	GetConversationsResp = pb2.GetConversationsResp
	GetMessagesReq       = pb2.GetMessagesReq
	GetMessagesResp      = pb2.GetMessagesResp
	GetNotificationsReq  = pb2.GetNotificationsReq
	GetNotificationsResp = pb2.GetNotificationsResp
	GetUnreadCountReq    = pb2.GetUnreadCountReq
	GetUnreadCountResp   = pb2.GetUnreadCountResp
	MarkReadReq          = pb2.MarkReadReq
	MarkReadResp         = pb2.MarkReadResp
	MessageInfo          = pb2.MessageInfo
	NotificationInfo     = pb2.NotificationInfo
	SendMessageReq       = pb2.SendMessageReq
	SendMessageResp      = pb2.SendMessageResp
	SendNotificationReq  = pb2.SendNotificationReq
	SendNotificationResp = pb2.SendNotificationResp

	MessageService interface {
		// 发送私信
		SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
		// 获取会话列表
		GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
		// 获取聊天记录
		GetMessages(ctx context.Context, in *GetMessagesReq, opts ...grpc.CallOption) (*GetMessagesResp, error)
		// 标记已读
		MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadResp, error)
		// 获取未读数
		GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
		// 发送系统通知
		SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error)
		// 获取通知列表
		GetNotifications(ctx context.Context, in *GetNotificationsReq, opts ...grpc.CallOption) (*GetNotificationsResp, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

// 发送私信
func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// 获取会话列表
func (m *defaultMessageService) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

// 获取聊天记录
func (m *defaultMessageService) GetMessages(ctx context.Context, in *GetMessagesReq, opts ...grpc.CallOption) (*GetMessagesResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}

// 标记已读
func (m *defaultMessageService) MarkRead(ctx context.Context, in *MarkReadReq, opts ...grpc.CallOption) (*MarkReadResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

// 获取未读数
func (m *defaultMessageService) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

// 发送系统通知
func (m *defaultMessageService) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.SendNotification(ctx, in, opts...)
}

// 获取通知列表
func (m *defaultMessageService) GetNotifications(ctx context.Context, in *GetNotificationsReq, opts ...grpc.CallOption) (*GetNotificationsResp, error) {
	client := pb2.NewMessageServiceClient(m.cli.Conn())
	return client.GetNotifications(ctx, in, opts...)
}
