// Code generated by Kitex v0.16.2. DO NOT EDIT.

package recommendservice

import (
	"context"
	recommend "esx/kitex_gen/recommend"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetRecommendPosts(ctx context.Context, Req *recommend.GetRecommendPostsReq, callOptions ...callopt.Option) (r *recommend.GetRecommendPostsResp, err error)
	GetSimilarPosts(ctx context.Context, Req *recommend.GetSimilarPostsReq, callOptions ...callopt.Option) (r *recommend.GetSimilarPostsResp, err error)
	GetRecommendUsers(ctx context.Context, Req *recommend.GetRecommendUsersReq, callOptions ...callopt.Option) (r *recommend.GetRecommendUsersResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRecommendServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRecommendServiceClient struct {
	*kClient
}

func (p *kRecommendServiceClient) GetRecommendPosts(ctx context.Context, Req *recommend.GetRecommendPostsReq, callOptions ...callopt.Option) (r *recommend.GetRecommendPostsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendPosts(ctx, Req)
}

func (p *kRecommendServiceClient) GetSimilarPosts(ctx context.Context, Req *recommend.GetSimilarPostsReq, callOptions ...callopt.Option) (r *recommend.GetSimilarPostsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSimilarPosts(ctx, Req)
}

func (p *kRecommendServiceClient) GetRecommendUsers(ctx context.Context, Req *recommend.GetRecommendUsersReq, callOptions ...callopt.Option) (r *recommend.GetRecommendUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendUsers(ctx, Req)
}
