// Code generated by scripts/generate_rpc_adapters.py. DO NOT EDIT.

package server

import (
	"context"
	"esx/app/assistant/rpc/internal/logic"
	"esx/app/assistant/rpc/internal/svc"
	pb "esx/kitex_gen/assistant"
)

type AssistantServiceServer struct{ svcCtx *svc.ServiceContext }

func NewAssistantServiceServer(ctx *svc.ServiceContext) *AssistantServiceServer {
	return &AssistantServiceServer{svcCtx: ctx}
}
func (s *AssistantServiceServer) GetThread(ctx context.Context, req *pb.GetThreadReq) (*pb.GetThreadResp, error) {
	return logic.NewGetThreadLogic(ctx, s.svcCtx).GetThread(req)
}
func (s *AssistantServiceServer) ListMessages(ctx context.Context, req *pb.ListMessagesReq) (*pb.ListMessagesResp, error) {
	return logic.NewListMessagesLogic(ctx, s.svcCtx).ListMessages(req)
}
func (s *AssistantServiceServer) PostMessage(ctx context.Context, req *pb.PostMessageReq) (*pb.PostMessageResp, error) {
	return logic.NewPostMessageLogic(ctx, s.svcCtx).PostMessage(req)
}
func (s *AssistantServiceServer) MarkThreadRead(ctx context.Context, req *pb.MarkThreadReadReq) (*pb.MarkThreadReadResp, error) {
	return logic.NewMarkThreadReadLogic(ctx, s.svcCtx).MarkThreadRead(req)
}
func (s *AssistantServiceServer) DeleteHistory(ctx context.Context, req *pb.DeleteHistoryReq) (*pb.DeleteHistoryResp, error) {
	return logic.NewDeleteHistoryLogic(ctx, s.svcCtx).DeleteHistory(req)
}
func (s *AssistantServiceServer) SubscribeRunEvents(req *pb.SubscribeRunEventsReq, stream pb.AssistantService_SubscribeRunEventsServer) error {
	return logic.NewSubscribeRunEventsLogic(stream.Context(), s.svcCtx).SubscribeRunEvents(req, stream)
}
func (s *AssistantServiceServer) CancelRun(ctx context.Context, req *pb.CancelRunReq) (*pb.CancelRunResp, error) {
	return logic.NewCancelRunLogic(ctx, s.svcCtx).CancelRun(req)
}
func (s *AssistantServiceServer) RevokeConsent(ctx context.Context, req *pb.RevokeConsentReq) (*pb.RevokeConsentResp, error) {
	return logic.NewRevokeConsentLogic(ctx, s.svcCtx).RevokeConsent(req)
}
func (s *AssistantServiceServer) ConfirmRunTool(ctx context.Context, req *pb.ConfirmRunToolReq) (*pb.ConfirmRunToolResp, error) {
	return logic.NewConfirmRunToolLogic(ctx, s.svcCtx).ConfirmRunTool(req)
}
func (s *AssistantServiceServer) AnswerQuestions(ctx context.Context, req *pb.AnswerQuestionsReq) (*pb.AnswerQuestionsResp, error) {
	return logic.NewAnswerQuestionsLogic(ctx, s.svcCtx).AnswerQuestions(req)
}
func (s *AssistantServiceServer) ListMemory(ctx context.Context, req *pb.ListMemoryReq) (*pb.ListMemoryResp, error) {
	return logic.NewListMemoryLogic(ctx, s.svcCtx).ListMemory(req)
}
func (s *AssistantServiceServer) AddMemory(ctx context.Context, req *pb.AddMemoryReq) (*pb.AddMemoryResp, error) {
	return logic.NewAddMemoryLogic(ctx, s.svcCtx).AddMemory(req)
}
func (s *AssistantServiceServer) ReplaceMemory(ctx context.Context, req *pb.ReplaceMemoryReq) (*pb.ReplaceMemoryResp, error) {
	return logic.NewReplaceMemoryLogic(ctx, s.svcCtx).ReplaceMemory(req)
}
func (s *AssistantServiceServer) RemoveMemory(ctx context.Context, req *pb.RemoveMemoryReq) (*pb.RemoveMemoryResp, error) {
	return logic.NewRemoveMemoryLogic(ctx, s.svcCtx).RemoveMemory(req)
}
func (s *AssistantServiceServer) BatchMemory(ctx context.Context, req *pb.BatchMemoryReq) (*pb.BatchMemoryResp, error) {
	return logic.NewBatchMemoryLogic(ctx, s.svcCtx).BatchMemory(req)
}
func (s *AssistantServiceServer) UndoMemoryChange(ctx context.Context, req *pb.UndoMemoryChangeReq) (*pb.UndoMemoryChangeResp, error) {
	return logic.NewUndoMemoryChangeLogic(ctx, s.svcCtx).UndoMemoryChange(req)
}
func (s *AssistantServiceServer) ListWatchTasks(ctx context.Context, req *pb.ListWatchTasksReq) (*pb.ListWatchTasksResp, error) {
	return logic.NewListWatchTasksLogic(ctx, s.svcCtx).ListWatchTasks(req)
}
func (s *AssistantServiceServer) CreateWatchTask(ctx context.Context, req *pb.CreateWatchTaskReq) (*pb.CreateWatchTaskResp, error) {
	return logic.NewCreateWatchTaskLogic(ctx, s.svcCtx).CreateWatchTask(req)
}
func (s *AssistantServiceServer) UpdateWatchTask(ctx context.Context, req *pb.UpdateWatchTaskReq) (*pb.UpdateWatchTaskResp, error) {
	return logic.NewUpdateWatchTaskLogic(ctx, s.svcCtx).UpdateWatchTask(req)
}
func (s *AssistantServiceServer) DeleteWatchTask(ctx context.Context, req *pb.DeleteWatchTaskReq) (*pb.DeleteWatchTaskResp, error) {
	return logic.NewDeleteWatchTaskLogic(ctx, s.svcCtx).DeleteWatchTask(req)
}
func (s *AssistantServiceServer) SubmitRecommendFeedback(ctx context.Context, req *pb.SubmitRecommendFeedbackReq) (*pb.SubmitRecommendFeedbackResp, error) {
	return logic.NewSubmitRecommendFeedbackLogic(ctx, s.svcCtx).SubmitRecommendFeedback(req)
}
