// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: media.proto

package server

import (
	"context"

	"esx/app/media/internal/logic"
	"esx/app/media/internal/svc"
	"esx/app/media/pb/xiaobaihe/media/pb"
)

type MediaServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMediaServiceServer
}

func NewMediaServiceServer(svcCtx *svc.ServiceContext) *MediaServiceServer {
	return &MediaServiceServer{
		svcCtx: svcCtx,
	}
}

// 上传图片（client streaming，每包 ≤ 1MB）
func (s *MediaServiceServer) UploadImage(stream pb.MediaService_UploadImageServer) error {
	l := logic.NewUploadImageLogic(stream.Context(), s.svcCtx)
	return l.UploadImage(stream)
}

// 上传视频（client streaming，每包 ≤ 1MB）
func (s *MediaServiceServer) UploadVideo(stream pb.MediaService_UploadVideoServer) error {
	l := logic.NewUploadVideoLogic(stream.Context(), s.svcCtx)
	return l.UploadVideo(stream)
}

// 获取媒体信息
func (s *MediaServiceServer) GetMedia(ctx context.Context, in *pb.GetMediaReq) (*pb.GetMediaResp, error) {
	l := logic.NewGetMediaLogic(ctx, s.svcCtx)
	return l.GetMedia(in)
}

// 删除媒体
func (s *MediaServiceServer) DeleteMedia(ctx context.Context, in *pb.DeleteMediaReq) (*pb.DeleteMediaResp, error) {
	l := logic.NewDeleteMediaLogic(ctx, s.svcCtx)
	return l.DeleteMedia(in)
}

// 批量获取媒体信息
func (s *MediaServiceServer) BatchGetMedia(ctx context.Context, in *pb.BatchGetMediaReq) (*pb.BatchGetMediaResp, error) {
	l := logic.NewBatchGetMediaLogic(ctx, s.svcCtx)
	return l.BatchGetMedia(in)
}
