// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/feed/feed.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FeedType      int32                  `protobuf:"varint,4,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"` // 1=follow 2=recommend
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_proto_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedItem) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FeedItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FeedItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FeedItem) GetFeedType() int32 {
	if x != nil {
		return x.FeedType
	}
	return 0
}

type GetFollowFeedReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CursorCreatedAt int64                  `protobuf:"varint,2,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"`
	CursorPostId    int64                  `protobuf:"varint,3,opt,name=cursor_post_id,json=cursorPostId,proto3" json:"cursor_post_id,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFollowFeedReq) Reset() {
	*x = GetFollowFeedReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowFeedReq) ProtoMessage() {}

func (x *GetFollowFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowFeedReq.ProtoReflect.Descriptor instead.
func (*GetFollowFeedReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowFeedReq) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *GetFollowFeedReq) GetCursorPostId() int64 {
	if x != nil {
		return x.CursorPostId
	}
	return 0
}

func (x *GetFollowFeedReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFollowFeedResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Items               []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore             bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,3,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorPostId    int64                  `protobuf:"varint,4,opt,name=next_cursor_post_id,json=nextCursorPostId,proto3" json:"next_cursor_post_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetFollowFeedResp) Reset() {
	*x = GetFollowFeedResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowFeedResp) ProtoMessage() {}

func (x *GetFollowFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowFeedResp.ProtoReflect.Descriptor instead.
func (*GetFollowFeedResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowFeedResp) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetFollowFeedResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetFollowFeedResp) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *GetFollowFeedResp) GetNextCursorPostId() int64 {
	if x != nil {
		return x.NextCursorPostId
	}
	return 0
}

type GetRecommendFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendFeedReq) Reset() {
	*x = GetRecommendFeedReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedReq) ProtoMessage() {}

func (x *GetRecommendFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedReq.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecommendFeedReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetRecommendFeedReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRecommendFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendFeedResp) Reset() {
	*x = GetRecommendFeedResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedResp) ProtoMessage() {}

func (x *GetRecommendFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedResp.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendFeedResp) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRecommendFeedResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type PushToInboxReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FollowerIds   []int64                `protobuf:"varint,4,rep,packed,name=follower_ids,json=followerIds,proto3" json:"follower_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToInboxReq) Reset() {
	*x = PushToInboxReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToInboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToInboxReq) ProtoMessage() {}

func (x *PushToInboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToInboxReq.ProtoReflect.Descriptor instead.
func (*PushToInboxReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{5}
}

func (x *PushToInboxReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PushToInboxReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PushToInboxReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PushToInboxReq) GetFollowerIds() []int64 {
	if x != nil {
		return x.FollowerIds
	}
	return nil
}

type PushToInboxResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushedCount   int64                  `protobuf:"varint,1,opt,name=pushed_count,json=pushedCount,proto3" json:"pushed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToInboxResp) Reset() {
	*x = PushToInboxResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToInboxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToInboxResp) ProtoMessage() {}

func (x *PushToInboxResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToInboxResp.ProtoReflect.Descriptor instead.
func (*PushToInboxResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{6}
}

func (x *PushToInboxResp) GetPushedCount() int64 {
	if x != nil {
		return x.PushedCount
	}
	return 0
}

type FanoutPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanoutPostReq) Reset() {
	*x = FanoutPostReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanoutPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutPostReq) ProtoMessage() {}

func (x *FanoutPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutPostReq.ProtoReflect.Descriptor instead.
func (*FanoutPostReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{7}
}

func (x *FanoutPostReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FanoutPostReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FanoutPostReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type FanoutPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushedCount   int64                  `protobuf:"varint,1,opt,name=pushed_count,json=pushedCount,proto3" json:"pushed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanoutPostResp) Reset() {
	*x = FanoutPostResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanoutPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutPostResp) ProtoMessage() {}

func (x *FanoutPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutPostResp.ProtoReflect.Descriptor instead.
func (*FanoutPostResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{8}
}

func (x *FanoutPostResp) GetPushedCount() int64 {
	if x != nil {
		return x.PushedCount
	}
	return 0
}

var File_proto_feed_feed_proto protoreflect.FileDescriptor

const file_proto_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x15proto/feed/feed.proto\x12\x04feed\"|\n" +
	"\bFeedItem\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tfeed_type\x18\x04 \x01(\x05R\bfeedType\"\x9a\x01\n" +
	"\x10GetFollowFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12*\n" +
	"\x11cursor_created_at\x18\x02 \x01(\x03R\x0fcursorCreatedAt\x12$\n" +
	"\x0ecursor_post_id\x18\x03 \x01(\x03R\fcursorPostId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb8\x01\n" +
	"\x11GetFollowFeedResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x123\n" +
	"\x16next_cursor_created_at\x18\x03 \x01(\x03R\x13nextCursorCreatedAt\x12-\n" +
	"\x13next_cursor_post_id\x18\x04 \x01(\x03R\x10nextCursorPostId\"_\n" +
	"\x13GetRecommendFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"W\n" +
	"\x14GetRecommendFeedResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\x88\x01\n" +
	"\x0ePushToInboxReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12!\n" +
	"\ffollower_ids\x18\x04 \x03(\x03R\vfollowerIds\"4\n" +
	"\x0fPushToInboxResp\x12!\n" +
	"\fpushed_count\x18\x01 \x01(\x03R\vpushedCount\"d\n" +
	"\rFanoutPostReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"3\n" +
	"\x0eFanoutPostResp\x12!\n" +
	"\fpushed_count\x18\x01 \x01(\x03R\vpushedCount2\x8f\x02\n" +
	"\vFeedService\x12@\n" +
	"\rGetFollowFeed\x12\x16.feed.GetFollowFeedReq\x1a\x17.feed.GetFollowFeedResp\x12I\n" +
	"\x10GetRecommendFeed\x12\x19.feed.GetRecommendFeedReq\x1a\x1a.feed.GetRecommendFeedResp\x12:\n" +
	"\vPushToInbox\x12\x14.feed.PushToInboxReq\x1a\x15.feed.PushToInboxResp\x127\n" +
	"\n" +
	"FanoutPost\x12\x13.feed.FanoutPostReq\x1a\x14.feed.FanoutPostRespB\x13Z\x11xiaobaihe/feed/pbb\x06proto3"

var (
	file_proto_feed_feed_proto_rawDescOnce sync.Once
	file_proto_feed_feed_proto_rawDescData []byte
)

func file_proto_feed_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_feed_proto_rawDesc), len(file_proto_feed_feed_proto_rawDesc)))
	})
	return file_proto_feed_feed_proto_rawDescData
}

var file_proto_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_feed_feed_proto_goTypes = []any{
	(*FeedItem)(nil),             // 0: feed.FeedItem
	(*GetFollowFeedReq)(nil),     // 1: feed.GetFollowFeedReq
	(*GetFollowFeedResp)(nil),    // 2: feed.GetFollowFeedResp
	(*GetRecommendFeedReq)(nil),  // 3: feed.GetRecommendFeedReq
	(*GetRecommendFeedResp)(nil), // 4: feed.GetRecommendFeedResp
	(*PushToInboxReq)(nil),       // 5: feed.PushToInboxReq
	(*PushToInboxResp)(nil),      // 6: feed.PushToInboxResp
	(*FanoutPostReq)(nil),        // 7: feed.FanoutPostReq
	(*FanoutPostResp)(nil),       // 8: feed.FanoutPostResp
}
var file_proto_feed_feed_proto_depIdxs = []int32{
	0, // 0: feed.GetFollowFeedResp.items:type_name -> feed.FeedItem
	0, // 1: feed.GetRecommendFeedResp.items:type_name -> feed.FeedItem
	1, // 2: feed.FeedService.GetFollowFeed:input_type -> feed.GetFollowFeedReq
	3, // 3: feed.FeedService.GetRecommendFeed:input_type -> feed.GetRecommendFeedReq
	5, // 4: feed.FeedService.PushToInbox:input_type -> feed.PushToInboxReq
	7, // 5: feed.FeedService.FanoutPost:input_type -> feed.FanoutPostReq
	2, // 6: feed.FeedService.GetFollowFeed:output_type -> feed.GetFollowFeedResp
	4, // 7: feed.FeedService.GetRecommendFeed:output_type -> feed.GetRecommendFeedResp
	6, // 8: feed.FeedService.PushToInbox:output_type -> feed.PushToInboxResp
	8, // 9: feed.FeedService.FanoutPost:output_type -> feed.FanoutPostResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_feed_feed_proto_init() }
func file_proto_feed_feed_proto_init() {
	if File_proto_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_feed_proto_rawDesc), len(file_proto_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_feed_proto = out.File
	file_proto_feed_feed_proto_goTypes = nil
	file_proto_feed_feed_proto_depIdxs = nil
}
