// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/feed/feed.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FeedType      int32                  `protobuf:"varint,4,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"` // 1=follow 2=recommend
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	RecallSource  string                 `protobuf:"bytes,7,opt,name=recall_source,json=recallSource,proto3" json:"recall_source,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,8,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,9,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	Position      int32                  `protobuf:"varint,10,opt,name=position,proto3" json:"position,omitempty"`
	Title         string                 `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,12,opt,name=content,proto3" json:"content,omitempty"`
	Images        []string               `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`
	Tags          []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	ViewCount     int64                  `protobuf:"varint,15,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,16,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,17,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,18,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_proto_feed_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{0}
}

func (x *FeedItem) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FeedItem) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FeedItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FeedItem) GetFeedType() int32 {
	if x != nil {
		return x.FeedType
	}
	return 0
}

func (x *FeedItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *FeedItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FeedItem) GetRecallSource() string {
	if x != nil {
		return x.RecallSource
	}
	return ""
}

func (x *FeedItem) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *FeedItem) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *FeedItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *FeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FeedItem) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *FeedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FeedItem) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *FeedItem) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *FeedItem) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *FeedItem) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

type GetFollowFeedReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CursorCreatedAt int64                  `protobuf:"varint,2,opt,name=cursor_created_at,json=cursorCreatedAt,proto3" json:"cursor_created_at,omitempty"`
	CursorPostId    int64                  `protobuf:"varint,3,opt,name=cursor_post_id,json=cursorPostId,proto3" json:"cursor_post_id,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFollowFeedReq) Reset() {
	*x = GetFollowFeedReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowFeedReq) ProtoMessage() {}

func (x *GetFollowFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowFeedReq.ProtoReflect.Descriptor instead.
func (*GetFollowFeedReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFollowFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFollowFeedReq) GetCursorCreatedAt() int64 {
	if x != nil {
		return x.CursorCreatedAt
	}
	return 0
}

func (x *GetFollowFeedReq) GetCursorPostId() int64 {
	if x != nil {
		return x.CursorPostId
	}
	return 0
}

func (x *GetFollowFeedReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFollowFeedResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Items               []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore             bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursorCreatedAt int64                  `protobuf:"varint,3,opt,name=next_cursor_created_at,json=nextCursorCreatedAt,proto3" json:"next_cursor_created_at,omitempty"`
	NextCursorPostId    int64                  `protobuf:"varint,4,opt,name=next_cursor_post_id,json=nextCursorPostId,proto3" json:"next_cursor_post_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetFollowFeedResp) Reset() {
	*x = GetFollowFeedResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowFeedResp) ProtoMessage() {}

func (x *GetFollowFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowFeedResp.ProtoReflect.Descriptor instead.
func (*GetFollowFeedResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowFeedResp) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetFollowFeedResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetFollowFeedResp) GetNextCursorCreatedAt() int64 {
	if x != nil {
		return x.NextCursorCreatedAt
	}
	return 0
}

func (x *GetFollowFeedResp) GetNextCursorPostId() int64 {
	if x != nil {
		return x.NextCursorPostId
	}
	return 0
}

type GetRecommendFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnonymousId   string                 `protobuf:"bytes,2,opt,name=anonymous_id,json=anonymousId,proto3" json:"anonymous_id,omitempty"`
	Scene         string                 `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,8,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendFeedReq) Reset() {
	*x = GetRecommendFeedReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedReq) ProtoMessage() {}

func (x *GetRecommendFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedReq.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecommendFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRecommendFeedReq) GetAnonymousId() string {
	if x != nil {
		return x.AnonymousId
	}
	return ""
}

func (x *GetRecommendFeedReq) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *GetRecommendFeedReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetRecommendFeedReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetRecommendFeedReq) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetRecommendFeedReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetRecommendFeedReq) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

type GetRecommendFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FeedItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendFeedResp) Reset() {
	*x = GetRecommendFeedResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendFeedResp) ProtoMessage() {}

func (x *GetRecommendFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendFeedResp.ProtoReflect.Descriptor instead.
func (*GetRecommendFeedResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecommendFeedResp) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRecommendFeedResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetRecommendFeedResp) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetRecommendFeedResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PushToInboxReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FollowerIds   []int64                `protobuf:"varint,4,rep,packed,name=follower_ids,json=followerIds,proto3" json:"follower_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToInboxReq) Reset() {
	*x = PushToInboxReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToInboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToInboxReq) ProtoMessage() {}

func (x *PushToInboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToInboxReq.ProtoReflect.Descriptor instead.
func (*PushToInboxReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{5}
}

func (x *PushToInboxReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PushToInboxReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PushToInboxReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PushToInboxReq) GetFollowerIds() []int64 {
	if x != nil {
		return x.FollowerIds
	}
	return nil
}

type PushToInboxResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushedCount   int64                  `protobuf:"varint,1,opt,name=pushed_count,json=pushedCount,proto3" json:"pushed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToInboxResp) Reset() {
	*x = PushToInboxResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToInboxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToInboxResp) ProtoMessage() {}

func (x *PushToInboxResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToInboxResp.ProtoReflect.Descriptor instead.
func (*PushToInboxResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{6}
}

func (x *PushToInboxResp) GetPushedCount() int64 {
	if x != nil {
		return x.PushedCount
	}
	return 0
}

type FanoutPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int64                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanoutPostReq) Reset() {
	*x = FanoutPostReq{}
	mi := &file_proto_feed_feed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanoutPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutPostReq) ProtoMessage() {}

func (x *FanoutPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutPostReq.ProtoReflect.Descriptor instead.
func (*FanoutPostReq) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{7}
}

func (x *FanoutPostReq) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *FanoutPostReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *FanoutPostReq) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type FanoutPostResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushedCount   int64                  `protobuf:"varint,1,opt,name=pushed_count,json=pushedCount,proto3" json:"pushed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanoutPostResp) Reset() {
	*x = FanoutPostResp{}
	mi := &file_proto_feed_feed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanoutPostResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanoutPostResp) ProtoMessage() {}

func (x *FanoutPostResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feed_feed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanoutPostResp.ProtoReflect.Descriptor instead.
func (*FanoutPostResp) Descriptor() ([]byte, []int) {
	return file_proto_feed_feed_proto_rawDescGZIP(), []int{8}
}

func (x *FanoutPostResp) GetPushedCount() int64 {
	if x != nil {
		return x.PushedCount
	}
	return 0
}

var File_proto_feed_feed_proto protoreflect.FileDescriptor

const file_proto_feed_feed_proto_rawDesc = "" +
	"\n" +
	"\x15proto/feed/feed.proto\x12\x04feed\"\x9b\x04\n" +
	"\bFeedItem\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tfeed_type\x18\x04 \x01(\x05R\bfeedType\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12#\n" +
	"\rrecall_source\x18\a \x01(\tR\frecallSource\x12#\n" +
	"\rmodel_version\x18\b \x01(\tR\fmodelVersion\x12#\n" +
	"\rexperiment_id\x18\t \x01(\tR\fexperimentId\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\x05R\bposition\x12\x14\n" +
	"\x05title\x18\v \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\f \x01(\tR\acontent\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06images\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"view_count\x18\x0f \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x10 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x11 \x01(\x03R\fcommentCount\x12%\n" +
	"\x0efavorite_count\x18\x12 \x01(\x03R\rfavoriteCount\"\x9a\x01\n" +
	"\x10GetFollowFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12*\n" +
	"\x11cursor_created_at\x18\x02 \x01(\x03R\x0fcursorCreatedAt\x12$\n" +
	"\x0ecursor_post_id\x18\x03 \x01(\x03R\fcursorPostId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb8\x01\n" +
	"\x11GetFollowFeedResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x123\n" +
	"\x16next_cursor_created_at\x18\x03 \x01(\x03R\x13nextCursorCreatedAt\x12-\n" +
	"\x13next_cursor_post_id\x18\x04 \x01(\x03R\x10nextCursorPostId\"\xff\x01\n" +
	"\x13GetRecommendFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fanonymous_id\x18\x02 \x01(\tR\vanonymousId\x12\x14\n" +
	"\x05scene\x18\x03 \x01(\tR\x05scene\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12#\n" +
	"\rexperiment_id\x18\b \x01(\tR\fexperimentId\"\x97\x01\n" +
	"\x14GetRecommendFeedResp\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.feed.FeedItemR\x05items\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x88\x01\n" +
	"\x0ePushToInboxReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12!\n" +
	"\ffollower_ids\x18\x04 \x03(\x03R\vfollowerIds\"4\n" +
	"\x0fPushToInboxResp\x12!\n" +
	"\fpushed_count\x18\x01 \x01(\x03R\vpushedCount\"d\n" +
	"\rFanoutPostReq\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x03R\bauthorId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x03R\x06postId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"3\n" +
	"\x0eFanoutPostResp\x12!\n" +
	"\fpushed_count\x18\x01 \x01(\x03R\vpushedCount2\x8f\x02\n" +
	"\vFeedService\x12@\n" +
	"\rGetFollowFeed\x12\x16.feed.GetFollowFeedReq\x1a\x17.feed.GetFollowFeedResp\x12I\n" +
	"\x10GetRecommendFeed\x12\x19.feed.GetRecommendFeedReq\x1a\x1a.feed.GetRecommendFeedResp\x12:\n" +
	"\vPushToInbox\x12\x14.feed.PushToInboxReq\x1a\x15.feed.PushToInboxResp\x127\n" +
	"\n" +
	"FanoutPost\x12\x13.feed.FanoutPostReq\x1a\x14.feed.FanoutPostRespB\x13Z\x11xiaobaihe/feed/pbb\x06proto3"

var (
	file_proto_feed_feed_proto_rawDescOnce sync.Once
	file_proto_feed_feed_proto_rawDescData []byte
)

func file_proto_feed_feed_proto_rawDescGZIP() []byte {
	file_proto_feed_feed_proto_rawDescOnce.Do(func() {
		file_proto_feed_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_feed_feed_proto_rawDesc), len(file_proto_feed_feed_proto_rawDesc)))
	})
	return file_proto_feed_feed_proto_rawDescData
}

var file_proto_feed_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_feed_feed_proto_goTypes = []any{
	(*FeedItem)(nil),             // 0: feed.FeedItem
	(*GetFollowFeedReq)(nil),     // 1: feed.GetFollowFeedReq
	(*GetFollowFeedResp)(nil),    // 2: feed.GetFollowFeedResp
	(*GetRecommendFeedReq)(nil),  // 3: feed.GetRecommendFeedReq
	(*GetRecommendFeedResp)(nil), // 4: feed.GetRecommendFeedResp
	(*PushToInboxReq)(nil),       // 5: feed.PushToInboxReq
	(*PushToInboxResp)(nil),      // 6: feed.PushToInboxResp
	(*FanoutPostReq)(nil),        // 7: feed.FanoutPostReq
	(*FanoutPostResp)(nil),       // 8: feed.FanoutPostResp
}
var file_proto_feed_feed_proto_depIdxs = []int32{
	0, // 0: feed.GetFollowFeedResp.items:type_name -> feed.FeedItem
	0, // 1: feed.GetRecommendFeedResp.items:type_name -> feed.FeedItem
	1, // 2: feed.FeedService.GetFollowFeed:input_type -> feed.GetFollowFeedReq
	3, // 3: feed.FeedService.GetRecommendFeed:input_type -> feed.GetRecommendFeedReq
	5, // 4: feed.FeedService.PushToInbox:input_type -> feed.PushToInboxReq
	7, // 5: feed.FeedService.FanoutPost:input_type -> feed.FanoutPostReq
	2, // 6: feed.FeedService.GetFollowFeed:output_type -> feed.GetFollowFeedResp
	4, // 7: feed.FeedService.GetRecommendFeed:output_type -> feed.GetRecommendFeedResp
	6, // 8: feed.FeedService.PushToInbox:output_type -> feed.PushToInboxResp
	8, // 9: feed.FeedService.FanoutPost:output_type -> feed.FanoutPostResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_feed_feed_proto_init() }
func file_proto_feed_feed_proto_init() {
	if File_proto_feed_feed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_feed_feed_proto_rawDesc), len(file_proto_feed_feed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feed_feed_proto_goTypes,
		DependencyIndexes: file_proto_feed_feed_proto_depIdxs,
		MessageInfos:      file_proto_feed_feed_proto_msgTypes,
	}.Build()
	File_proto_feed_feed_proto = out.File
	file_proto_feed_feed_proto_goTypes = nil
	file_proto_feed_feed_proto_depIdxs = nil
}
