// Code generated by Kitex v0.16.2. DO NOT EDIT.

package searchservice

import (
	"context"
	search "esx/kitex_gen/search"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SearchPosts(ctx context.Context, Req *search.SearchPostsReq, callOptions ...callopt.Option) (r *search.SearchPostsResp, err error)
	SearchUsers(ctx context.Context, Req *search.SearchUsersReq, callOptions ...callopt.Option) (r *search.SearchUsersResp, err error)
	SearchTags(ctx context.Context, Req *search.SearchTagsReq, callOptions ...callopt.Option) (r *search.SearchTagsResp, err error)
	Search(ctx context.Context, Req *search.SearchReq, callOptions ...callopt.Option) (r *search.SearchResp, err error)
	GetHotSearches(ctx context.Context, Req *search.GetHotSearchesReq, callOptions ...callopt.Option) (r *search.GetHotSearchesResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSearchServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSearchServiceClient struct {
	*kClient
}

func (p *kSearchServiceClient) SearchPosts(ctx context.Context, Req *search.SearchPostsReq, callOptions ...callopt.Option) (r *search.SearchPostsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchPosts(ctx, Req)
}

func (p *kSearchServiceClient) SearchUsers(ctx context.Context, Req *search.SearchUsersReq, callOptions ...callopt.Option) (r *search.SearchUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchUsers(ctx, Req)
}

func (p *kSearchServiceClient) SearchTags(ctx context.Context, Req *search.SearchTagsReq, callOptions ...callopt.Option) (r *search.SearchTagsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchTags(ctx, Req)
}

func (p *kSearchServiceClient) Search(ctx context.Context, Req *search.SearchReq, callOptions ...callopt.Option) (r *search.SearchResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Search(ctx, Req)
}

func (p *kSearchServiceClient) GetHotSearches(ctx context.Context, Req *search.GetHotSearchesReq, callOptions ...callopt.Option) (r *search.GetHotSearchesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetHotSearches(ctx, Req)
}
