// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: content.proto

package contentservice

import (
	"context"

	"esx/app/content/pb/xiaobaihe/content/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateCommentReq   = pb.CreateCommentReq
	CreateCommentResp  = pb.CreateCommentResp
	CreatePostReq      = pb.CreatePostReq
	CreatePostResp     = pb.CreatePostResp
	DeleteCommentReq   = pb.DeleteCommentReq
	DeleteCommentResp  = pb.DeleteCommentResp
	DeletePostReq      = pb.DeletePostReq
	DeletePostResp     = pb.DeletePostResp
	GetCommentListReq  = pb.GetCommentListReq
	GetCommentListResp = pb.GetCommentListResp
	GetPostListReq     = pb.GetPostListReq
	GetPostListResp    = pb.GetPostListResp
	GetPostReq         = pb.GetPostReq
	GetPostResp        = pb.GetPostResp
	GetPostsByIdsReq   = pb.GetPostsByIdsReq
	GetPostsByIdsResp  = pb.GetPostsByIdsResp
	GetPostsByTagReq   = pb.GetPostsByTagReq
	GetPostsByTagResp  = pb.GetPostsByTagResp
	GetTagsReq         = pb.GetTagsReq
	GetTagsResp        = pb.GetTagsResp
	GetUserPostsReq    = pb.GetUserPostsReq
	GetUserPostsResp   = pb.GetUserPostsResp
	UpdatePostReq      = pb.UpdatePostReq
	UpdatePostResp     = pb.UpdatePostResp

	ContentService interface {
		// 创建帖子
		CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error)
		// 获取帖子详情
		GetPost(ctx context.Context, in *GetPostReq, opts ...grpc.CallOption) (*GetPostResp, error)
		// 更新帖子
		UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error)
		// 删除帖子
		DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error)
		// 获取帖子列表
		GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error)
		// 获取用户帖子列表
		GetUserPosts(ctx context.Context, in *GetUserPostsReq, opts ...grpc.CallOption) (*GetUserPostsResp, error)
		// 按ID批量获取帖子
		GetPostsByIds(ctx context.Context, in *GetPostsByIdsReq, opts ...grpc.CallOption) (*GetPostsByIdsResp, error)
		// 创建评论
		CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error)
		// 删除评论
		DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error)
		// 获取评论列表
		GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error)
		// 获取标签列表
		GetTags(ctx context.Context, in *GetTagsReq, opts ...grpc.CallOption) (*GetTagsResp, error)
		// 获取标签下的帖子
		GetPostsByTag(ctx context.Context, in *GetPostsByTagReq, opts ...grpc.CallOption) (*GetPostsByTagResp, error)
	}

	defaultContentService struct {
		cli zrpc.Client
	}
)

func NewContentService(cli zrpc.Client) ContentService {
	return &defaultContentService{
		cli: cli,
	}
}

// 创建帖子
func (m *defaultContentService) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.CreatePost(ctx, in, opts...)
}

// 获取帖子详情
func (m *defaultContentService) GetPost(ctx context.Context, in *GetPostReq, opts ...grpc.CallOption) (*GetPostResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetPost(ctx, in, opts...)
}

// 更新帖子
func (m *defaultContentService) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.UpdatePost(ctx, in, opts...)
}

// 删除帖子
func (m *defaultContentService) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.DeletePost(ctx, in, opts...)
}

// 获取帖子列表
func (m *defaultContentService) GetPostList(ctx context.Context, in *GetPostListReq, opts ...grpc.CallOption) (*GetPostListResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetPostList(ctx, in, opts...)
}

// 获取用户帖子列表
func (m *defaultContentService) GetUserPosts(ctx context.Context, in *GetUserPostsReq, opts ...grpc.CallOption) (*GetUserPostsResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetUserPosts(ctx, in, opts...)
}

// 按ID批量获取帖子
func (m *defaultContentService) GetPostsByIds(ctx context.Context, in *GetPostsByIdsReq, opts ...grpc.CallOption) (*GetPostsByIdsResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetPostsByIds(ctx, in, opts...)
}

// 创建评论
func (m *defaultContentService) CreateComment(ctx context.Context, in *CreateCommentReq, opts ...grpc.CallOption) (*CreateCommentResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.CreateComment(ctx, in, opts...)
}

// 删除评论
func (m *defaultContentService) DeleteComment(ctx context.Context, in *DeleteCommentReq, opts ...grpc.CallOption) (*DeleteCommentResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.DeleteComment(ctx, in, opts...)
}

// 获取评论列表
func (m *defaultContentService) GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetCommentList(ctx, in, opts...)
}

// 获取标签列表
func (m *defaultContentService) GetTags(ctx context.Context, in *GetTagsReq, opts ...grpc.CallOption) (*GetTagsResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetTags(ctx, in, opts...)
}

// 获取标签下的帖子
func (m *defaultContentService) GetPostsByTag(ctx context.Context, in *GetPostsByTagReq, opts ...grpc.CallOption) (*GetPostsByTagResp, error) {
	client := pb.NewContentServiceClient(m.cli.Conn())
	return client.GetPostsByTag(ctx, in, opts...)
}
