// Code generated by Kitex v0.16.2. DO NOT EDIT.

package contentservice

import (
	"context"
	content "esx/kitex_gen/content"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreatePost(ctx context.Context, Req *content.CreatePostReq, callOptions ...callopt.Option) (r *content.CreatePostResp, err error)
	GetPost(ctx context.Context, Req *content.GetPostReq, callOptions ...callopt.Option) (r *content.GetPostResp, err error)
	UpdatePost(ctx context.Context, Req *content.UpdatePostReq, callOptions ...callopt.Option) (r *content.UpdatePostResp, err error)
	DeletePost(ctx context.Context, Req *content.DeletePostReq, callOptions ...callopt.Option) (r *content.DeletePostResp, err error)
	GetPostList(ctx context.Context, Req *content.GetPostListReq, callOptions ...callopt.Option) (r *content.GetPostListResp, err error)
	GetUserPosts(ctx context.Context, Req *content.GetUserPostsReq, callOptions ...callopt.Option) (r *content.GetUserPostsResp, err error)
	GetPostsByIds(ctx context.Context, Req *content.GetPostsByIdsReq, callOptions ...callopt.Option) (r *content.GetPostsByIdsResp, err error)
	CreateComment(ctx context.Context, Req *content.CreateCommentReq, callOptions ...callopt.Option) (r *content.CreateCommentResp, err error)
	DeleteComment(ctx context.Context, Req *content.DeleteCommentReq, callOptions ...callopt.Option) (r *content.DeleteCommentResp, err error)
	GetCommentList(ctx context.Context, Req *content.GetCommentListReq, callOptions ...callopt.Option) (r *content.GetCommentListResp, err error)
	GetCommentReplies(ctx context.Context, Req *content.GetCommentRepliesReq, callOptions ...callopt.Option) (r *content.GetCommentRepliesResp, err error)
	GetCommentsByIds(ctx context.Context, Req *content.GetCommentsByIdsReq, callOptions ...callopt.Option) (r *content.GetCommentsByIdsResp, err error)
	AssertInteractable(ctx context.Context, Req *content.AssertInteractableReq, callOptions ...callopt.Option) (r *content.AssertInteractableResp, err error)
	GetTags(ctx context.Context, Req *content.GetTagsReq, callOptions ...callopt.Option) (r *content.GetTagsResp, err error)
	GetPostsByTag(ctx context.Context, Req *content.GetPostsByTagReq, callOptions ...callopt.Option) (r *content.GetPostsByTagResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kContentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kContentServiceClient struct {
	*kClient
}

func (p *kContentServiceClient) CreatePost(ctx context.Context, Req *content.CreatePostReq, callOptions ...callopt.Option) (r *content.CreatePostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreatePost(ctx, Req)
}

func (p *kContentServiceClient) GetPost(ctx context.Context, Req *content.GetPostReq, callOptions ...callopt.Option) (r *content.GetPostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPost(ctx, Req)
}

func (p *kContentServiceClient) UpdatePost(ctx context.Context, Req *content.UpdatePostReq, callOptions ...callopt.Option) (r *content.UpdatePostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePost(ctx, Req)
}

func (p *kContentServiceClient) DeletePost(ctx context.Context, Req *content.DeletePostReq, callOptions ...callopt.Option) (r *content.DeletePostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeletePost(ctx, Req)
}

func (p *kContentServiceClient) GetPostList(ctx context.Context, Req *content.GetPostListReq, callOptions ...callopt.Option) (r *content.GetPostListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPostList(ctx, Req)
}

func (p *kContentServiceClient) GetUserPosts(ctx context.Context, Req *content.GetUserPostsReq, callOptions ...callopt.Option) (r *content.GetUserPostsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserPosts(ctx, Req)
}

func (p *kContentServiceClient) GetPostsByIds(ctx context.Context, Req *content.GetPostsByIdsReq, callOptions ...callopt.Option) (r *content.GetPostsByIdsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPostsByIds(ctx, Req)
}

func (p *kContentServiceClient) CreateComment(ctx context.Context, Req *content.CreateCommentReq, callOptions ...callopt.Option) (r *content.CreateCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateComment(ctx, Req)
}

func (p *kContentServiceClient) DeleteComment(ctx context.Context, Req *content.DeleteCommentReq, callOptions ...callopt.Option) (r *content.DeleteCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteComment(ctx, Req)
}

func (p *kContentServiceClient) GetCommentList(ctx context.Context, Req *content.GetCommentListReq, callOptions ...callopt.Option) (r *content.GetCommentListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, Req)
}

func (p *kContentServiceClient) GetCommentReplies(ctx context.Context, Req *content.GetCommentRepliesReq, callOptions ...callopt.Option) (r *content.GetCommentRepliesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentReplies(ctx, Req)
}

func (p *kContentServiceClient) GetCommentsByIds(ctx context.Context, Req *content.GetCommentsByIdsReq, callOptions ...callopt.Option) (r *content.GetCommentsByIdsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentsByIds(ctx, Req)
}

func (p *kContentServiceClient) AssertInteractable(ctx context.Context, Req *content.AssertInteractableReq, callOptions ...callopt.Option) (r *content.AssertInteractableResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssertInteractable(ctx, Req)
}

func (p *kContentServiceClient) GetTags(ctx context.Context, Req *content.GetTagsReq, callOptions ...callopt.Option) (r *content.GetTagsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTags(ctx, Req)
}

func (p *kContentServiceClient) GetPostsByTag(ctx context.Context, Req *content.GetPostsByTagReq, callOptions ...callopt.Option) (r *content.GetPostsByTagResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPostsByTag(ctx, Req)
}
