// Code generated by Kitex v0.16.2. DO NOT EDIT.

package contentservice

import (
	"context"
	"errors"
	content "esx/kitex_gen/content"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreatePost": kitex.NewMethodInfo(
		createPostHandler,
		newCreatePostArgs,
		newCreatePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPost": kitex.NewMethodInfo(
		getPostHandler,
		newGetPostArgs,
		newGetPostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"UpdatePost": kitex.NewMethodInfo(
		updatePostHandler,
		newUpdatePostArgs,
		newUpdatePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeletePost": kitex.NewMethodInfo(
		deletePostHandler,
		newDeletePostArgs,
		newDeletePostResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPostList": kitex.NewMethodInfo(
		getPostListHandler,
		newGetPostListArgs,
		newGetPostListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetUserPosts": kitex.NewMethodInfo(
		getUserPostsHandler,
		newGetUserPostsArgs,
		newGetUserPostsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPostsByIds": kitex.NewMethodInfo(
		getPostsByIdsHandler,
		newGetPostsByIdsArgs,
		newGetPostsByIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CreateComment": kitex.NewMethodInfo(
		createCommentHandler,
		newCreateCommentArgs,
		newCreateCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"DeleteComment": kitex.NewMethodInfo(
		deleteCommentHandler,
		newDeleteCommentArgs,
		newDeleteCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCommentList": kitex.NewMethodInfo(
		getCommentListHandler,
		newGetCommentListArgs,
		newGetCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCommentReplies": kitex.NewMethodInfo(
		getCommentRepliesHandler,
		newGetCommentRepliesArgs,
		newGetCommentRepliesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetCommentsByIds": kitex.NewMethodInfo(
		getCommentsByIdsHandler,
		newGetCommentsByIdsArgs,
		newGetCommentsByIdsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AssertInteractable": kitex.NewMethodInfo(
		assertInteractableHandler,
		newAssertInteractableArgs,
		newAssertInteractableResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetTags": kitex.NewMethodInfo(
		getTagsHandler,
		newGetTagsArgs,
		newGetTagsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPostsByTag": kitex.NewMethodInfo(
		getPostsByTagHandler,
		newGetPostsByTagArgs,
		newGetPostsByTagResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	contentServiceServiceInfo                = NewServiceInfo()
	contentServiceServiceInfoForClient       = NewServiceInfoForClient()
	contentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return contentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return contentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return contentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ContentService"
	handlerType := (*content.ContentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "content",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.CreatePostReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).CreatePost(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreatePostArgs:
		success, err := handler.(content.ContentService).CreatePost(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreatePostResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreatePostArgs() interface{} {
	return &CreatePostArgs{}
}

func newCreatePostResult() interface{} {
	return &CreatePostResult{}
}

type CreatePostArgs struct {
	Req *content.CreatePostReq
}

func (p *CreatePostArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreatePostArgs) Unmarshal(in []byte) error {
	msg := new(content.CreatePostReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreatePostArgs_Req_DEFAULT *content.CreatePostReq

func (p *CreatePostArgs) GetReq() *content.CreatePostReq {
	if !p.IsSetReq() {
		return CreatePostArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreatePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreatePostArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreatePostResult struct {
	Success *content.CreatePostResp
}

var CreatePostResult_Success_DEFAULT *content.CreatePostResp

func (p *CreatePostResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreatePostResult) Unmarshal(in []byte) error {
	msg := new(content.CreatePostResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreatePostResult) GetSuccess() *content.CreatePostResp {
	if !p.IsSetSuccess() {
		return CreatePostResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreatePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.CreatePostResp)
}

func (p *CreatePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreatePostResult) GetResult() interface{} {
	return p.Success
}

func getPostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetPostReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetPost(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPostArgs:
		success, err := handler.(content.ContentService).GetPost(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPostResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPostArgs() interface{} {
	return &GetPostArgs{}
}

func newGetPostResult() interface{} {
	return &GetPostResult{}
}

type GetPostArgs struct {
	Req *content.GetPostReq
}

func (p *GetPostArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPostArgs) Unmarshal(in []byte) error {
	msg := new(content.GetPostReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPostArgs_Req_DEFAULT *content.GetPostReq

func (p *GetPostArgs) GetReq() *content.GetPostReq {
	if !p.IsSetReq() {
		return GetPostArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPostArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPostResult struct {
	Success *content.GetPostResp
}

var GetPostResult_Success_DEFAULT *content.GetPostResp

func (p *GetPostResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPostResult) Unmarshal(in []byte) error {
	msg := new(content.GetPostResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPostResult) GetSuccess() *content.GetPostResp {
	if !p.IsSetSuccess() {
		return GetPostResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPostResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetPostResp)
}

func (p *GetPostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPostResult) GetResult() interface{} {
	return p.Success
}

func updatePostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.UpdatePostReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).UpdatePost(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UpdatePostArgs:
		success, err := handler.(content.ContentService).UpdatePost(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UpdatePostResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUpdatePostArgs() interface{} {
	return &UpdatePostArgs{}
}

func newUpdatePostResult() interface{} {
	return &UpdatePostResult{}
}

type UpdatePostArgs struct {
	Req *content.UpdatePostReq
}

func (p *UpdatePostArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UpdatePostArgs) Unmarshal(in []byte) error {
	msg := new(content.UpdatePostReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UpdatePostArgs_Req_DEFAULT *content.UpdatePostReq

func (p *UpdatePostArgs) GetReq() *content.UpdatePostReq {
	if !p.IsSetReq() {
		return UpdatePostArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UpdatePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UpdatePostArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UpdatePostResult struct {
	Success *content.UpdatePostResp
}

var UpdatePostResult_Success_DEFAULT *content.UpdatePostResp

func (p *UpdatePostResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UpdatePostResult) Unmarshal(in []byte) error {
	msg := new(content.UpdatePostResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UpdatePostResult) GetSuccess() *content.UpdatePostResp {
	if !p.IsSetSuccess() {
		return UpdatePostResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UpdatePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.UpdatePostResp)
}

func (p *UpdatePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UpdatePostResult) GetResult() interface{} {
	return p.Success
}

func deletePostHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.DeletePostReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).DeletePost(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeletePostArgs:
		success, err := handler.(content.ContentService).DeletePost(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeletePostResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeletePostArgs() interface{} {
	return &DeletePostArgs{}
}

func newDeletePostResult() interface{} {
	return &DeletePostResult{}
}

type DeletePostArgs struct {
	Req *content.DeletePostReq
}

func (p *DeletePostArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeletePostArgs) Unmarshal(in []byte) error {
	msg := new(content.DeletePostReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeletePostArgs_Req_DEFAULT *content.DeletePostReq

func (p *DeletePostArgs) GetReq() *content.DeletePostReq {
	if !p.IsSetReq() {
		return DeletePostArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeletePostArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeletePostArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeletePostResult struct {
	Success *content.DeletePostResp
}

var DeletePostResult_Success_DEFAULT *content.DeletePostResp

func (p *DeletePostResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeletePostResult) Unmarshal(in []byte) error {
	msg := new(content.DeletePostResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeletePostResult) GetSuccess() *content.DeletePostResp {
	if !p.IsSetSuccess() {
		return DeletePostResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeletePostResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.DeletePostResp)
}

func (p *DeletePostResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeletePostResult) GetResult() interface{} {
	return p.Success
}

func getPostListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetPostListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetPostList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPostListArgs:
		success, err := handler.(content.ContentService).GetPostList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPostListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPostListArgs() interface{} {
	return &GetPostListArgs{}
}

func newGetPostListResult() interface{} {
	return &GetPostListResult{}
}

type GetPostListArgs struct {
	Req *content.GetPostListReq
}

func (p *GetPostListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPostListArgs) Unmarshal(in []byte) error {
	msg := new(content.GetPostListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPostListArgs_Req_DEFAULT *content.GetPostListReq

func (p *GetPostListArgs) GetReq() *content.GetPostListReq {
	if !p.IsSetReq() {
		return GetPostListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPostListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPostListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPostListResult struct {
	Success *content.GetPostListResp
}

var GetPostListResult_Success_DEFAULT *content.GetPostListResp

func (p *GetPostListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPostListResult) Unmarshal(in []byte) error {
	msg := new(content.GetPostListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPostListResult) GetSuccess() *content.GetPostListResp {
	if !p.IsSetSuccess() {
		return GetPostListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPostListResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetPostListResp)
}

func (p *GetPostListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPostListResult) GetResult() interface{} {
	return p.Success
}

func getUserPostsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetUserPostsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetUserPosts(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetUserPostsArgs:
		success, err := handler.(content.ContentService).GetUserPosts(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetUserPostsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetUserPostsArgs() interface{} {
	return &GetUserPostsArgs{}
}

func newGetUserPostsResult() interface{} {
	return &GetUserPostsResult{}
}

type GetUserPostsArgs struct {
	Req *content.GetUserPostsReq
}

func (p *GetUserPostsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetUserPostsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetUserPostsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetUserPostsArgs_Req_DEFAULT *content.GetUserPostsReq

func (p *GetUserPostsArgs) GetReq() *content.GetUserPostsReq {
	if !p.IsSetReq() {
		return GetUserPostsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetUserPostsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetUserPostsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetUserPostsResult struct {
	Success *content.GetUserPostsResp
}

var GetUserPostsResult_Success_DEFAULT *content.GetUserPostsResp

func (p *GetUserPostsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetUserPostsResult) Unmarshal(in []byte) error {
	msg := new(content.GetUserPostsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetUserPostsResult) GetSuccess() *content.GetUserPostsResp {
	if !p.IsSetSuccess() {
		return GetUserPostsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetUserPostsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetUserPostsResp)
}

func (p *GetUserPostsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetUserPostsResult) GetResult() interface{} {
	return p.Success
}

func getPostsByIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetPostsByIdsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetPostsByIds(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPostsByIdsArgs:
		success, err := handler.(content.ContentService).GetPostsByIds(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPostsByIdsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPostsByIdsArgs() interface{} {
	return &GetPostsByIdsArgs{}
}

func newGetPostsByIdsResult() interface{} {
	return &GetPostsByIdsResult{}
}

type GetPostsByIdsArgs struct {
	Req *content.GetPostsByIdsReq
}

func (p *GetPostsByIdsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPostsByIdsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetPostsByIdsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPostsByIdsArgs_Req_DEFAULT *content.GetPostsByIdsReq

func (p *GetPostsByIdsArgs) GetReq() *content.GetPostsByIdsReq {
	if !p.IsSetReq() {
		return GetPostsByIdsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPostsByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPostsByIdsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPostsByIdsResult struct {
	Success *content.GetPostsByIdsResp
}

var GetPostsByIdsResult_Success_DEFAULT *content.GetPostsByIdsResp

func (p *GetPostsByIdsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPostsByIdsResult) Unmarshal(in []byte) error {
	msg := new(content.GetPostsByIdsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPostsByIdsResult) GetSuccess() *content.GetPostsByIdsResp {
	if !p.IsSetSuccess() {
		return GetPostsByIdsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPostsByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetPostsByIdsResp)
}

func (p *GetPostsByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPostsByIdsResult) GetResult() interface{} {
	return p.Success
}

func createCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.CreateCommentReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).CreateComment(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CreateCommentArgs:
		success, err := handler.(content.ContentService).CreateComment(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CreateCommentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCreateCommentArgs() interface{} {
	return &CreateCommentArgs{}
}

func newCreateCommentResult() interface{} {
	return &CreateCommentResult{}
}

type CreateCommentArgs struct {
	Req *content.CreateCommentReq
}

func (p *CreateCommentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CreateCommentArgs) Unmarshal(in []byte) error {
	msg := new(content.CreateCommentReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CreateCommentArgs_Req_DEFAULT *content.CreateCommentReq

func (p *CreateCommentArgs) GetReq() *content.CreateCommentReq {
	if !p.IsSetReq() {
		return CreateCommentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CreateCommentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CreateCommentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CreateCommentResult struct {
	Success *content.CreateCommentResp
}

var CreateCommentResult_Success_DEFAULT *content.CreateCommentResp

func (p *CreateCommentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CreateCommentResult) Unmarshal(in []byte) error {
	msg := new(content.CreateCommentResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CreateCommentResult) GetSuccess() *content.CreateCommentResp {
	if !p.IsSetSuccess() {
		return CreateCommentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CreateCommentResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.CreateCommentResp)
}

func (p *CreateCommentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CreateCommentResult) GetResult() interface{} {
	return p.Success
}

func deleteCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.DeleteCommentReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).DeleteComment(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *DeleteCommentArgs:
		success, err := handler.(content.ContentService).DeleteComment(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteCommentResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newDeleteCommentArgs() interface{} {
	return &DeleteCommentArgs{}
}

func newDeleteCommentResult() interface{} {
	return &DeleteCommentResult{}
}

type DeleteCommentArgs struct {
	Req *content.DeleteCommentReq
}

func (p *DeleteCommentArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteCommentArgs) Unmarshal(in []byte) error {
	msg := new(content.DeleteCommentReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteCommentArgs_Req_DEFAULT *content.DeleteCommentReq

func (p *DeleteCommentArgs) GetReq() *content.DeleteCommentReq {
	if !p.IsSetReq() {
		return DeleteCommentArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteCommentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DeleteCommentArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DeleteCommentResult struct {
	Success *content.DeleteCommentResp
}

var DeleteCommentResult_Success_DEFAULT *content.DeleteCommentResp

func (p *DeleteCommentResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteCommentResult) Unmarshal(in []byte) error {
	msg := new(content.DeleteCommentResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteCommentResult) GetSuccess() *content.DeleteCommentResp {
	if !p.IsSetSuccess() {
		return DeleteCommentResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteCommentResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.DeleteCommentResp)
}

func (p *DeleteCommentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DeleteCommentResult) GetResult() interface{} {
	return p.Success
}

func getCommentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetCommentListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetCommentList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCommentListArgs:
		success, err := handler.(content.ContentService).GetCommentList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCommentListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCommentListArgs() interface{} {
	return &GetCommentListArgs{}
}

func newGetCommentListResult() interface{} {
	return &GetCommentListResult{}
}

type GetCommentListArgs struct {
	Req *content.GetCommentListReq
}

func (p *GetCommentListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCommentListArgs) Unmarshal(in []byte) error {
	msg := new(content.GetCommentListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCommentListArgs_Req_DEFAULT *content.GetCommentListReq

func (p *GetCommentListArgs) GetReq() *content.GetCommentListReq {
	if !p.IsSetReq() {
		return GetCommentListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCommentListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCommentListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCommentListResult struct {
	Success *content.GetCommentListResp
}

var GetCommentListResult_Success_DEFAULT *content.GetCommentListResp

func (p *GetCommentListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCommentListResult) Unmarshal(in []byte) error {
	msg := new(content.GetCommentListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCommentListResult) GetSuccess() *content.GetCommentListResp {
	if !p.IsSetSuccess() {
		return GetCommentListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCommentListResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetCommentListResp)
}

func (p *GetCommentListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCommentListResult) GetResult() interface{} {
	return p.Success
}

func getCommentRepliesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetCommentRepliesReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetCommentReplies(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCommentRepliesArgs:
		success, err := handler.(content.ContentService).GetCommentReplies(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCommentRepliesResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCommentRepliesArgs() interface{} {
	return &GetCommentRepliesArgs{}
}

func newGetCommentRepliesResult() interface{} {
	return &GetCommentRepliesResult{}
}

type GetCommentRepliesArgs struct {
	Req *content.GetCommentRepliesReq
}

func (p *GetCommentRepliesArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCommentRepliesArgs) Unmarshal(in []byte) error {
	msg := new(content.GetCommentRepliesReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCommentRepliesArgs_Req_DEFAULT *content.GetCommentRepliesReq

func (p *GetCommentRepliesArgs) GetReq() *content.GetCommentRepliesReq {
	if !p.IsSetReq() {
		return GetCommentRepliesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCommentRepliesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCommentRepliesArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCommentRepliesResult struct {
	Success *content.GetCommentRepliesResp
}

var GetCommentRepliesResult_Success_DEFAULT *content.GetCommentRepliesResp

func (p *GetCommentRepliesResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCommentRepliesResult) Unmarshal(in []byte) error {
	msg := new(content.GetCommentRepliesResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCommentRepliesResult) GetSuccess() *content.GetCommentRepliesResp {
	if !p.IsSetSuccess() {
		return GetCommentRepliesResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCommentRepliesResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetCommentRepliesResp)
}

func (p *GetCommentRepliesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCommentRepliesResult) GetResult() interface{} {
	return p.Success
}

func getCommentsByIdsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetCommentsByIdsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetCommentsByIds(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetCommentsByIdsArgs:
		success, err := handler.(content.ContentService).GetCommentsByIds(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCommentsByIdsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetCommentsByIdsArgs() interface{} {
	return &GetCommentsByIdsArgs{}
}

func newGetCommentsByIdsResult() interface{} {
	return &GetCommentsByIdsResult{}
}

type GetCommentsByIdsArgs struct {
	Req *content.GetCommentsByIdsReq
}

func (p *GetCommentsByIdsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetCommentsByIdsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetCommentsByIdsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCommentsByIdsArgs_Req_DEFAULT *content.GetCommentsByIdsReq

func (p *GetCommentsByIdsArgs) GetReq() *content.GetCommentsByIdsReq {
	if !p.IsSetReq() {
		return GetCommentsByIdsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCommentsByIdsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetCommentsByIdsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetCommentsByIdsResult struct {
	Success *content.GetCommentsByIdsResp
}

var GetCommentsByIdsResult_Success_DEFAULT *content.GetCommentsByIdsResp

func (p *GetCommentsByIdsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetCommentsByIdsResult) Unmarshal(in []byte) error {
	msg := new(content.GetCommentsByIdsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCommentsByIdsResult) GetSuccess() *content.GetCommentsByIdsResp {
	if !p.IsSetSuccess() {
		return GetCommentsByIdsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCommentsByIdsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetCommentsByIdsResp)
}

func (p *GetCommentsByIdsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetCommentsByIdsResult) GetResult() interface{} {
	return p.Success
}

func assertInteractableHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.AssertInteractableReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).AssertInteractable(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AssertInteractableArgs:
		success, err := handler.(content.ContentService).AssertInteractable(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AssertInteractableResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAssertInteractableArgs() interface{} {
	return &AssertInteractableArgs{}
}

func newAssertInteractableResult() interface{} {
	return &AssertInteractableResult{}
}

type AssertInteractableArgs struct {
	Req *content.AssertInteractableReq
}

func (p *AssertInteractableArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AssertInteractableArgs) Unmarshal(in []byte) error {
	msg := new(content.AssertInteractableReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AssertInteractableArgs_Req_DEFAULT *content.AssertInteractableReq

func (p *AssertInteractableArgs) GetReq() *content.AssertInteractableReq {
	if !p.IsSetReq() {
		return AssertInteractableArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AssertInteractableArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AssertInteractableArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AssertInteractableResult struct {
	Success *content.AssertInteractableResp
}

var AssertInteractableResult_Success_DEFAULT *content.AssertInteractableResp

func (p *AssertInteractableResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AssertInteractableResult) Unmarshal(in []byte) error {
	msg := new(content.AssertInteractableResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AssertInteractableResult) GetSuccess() *content.AssertInteractableResp {
	if !p.IsSetSuccess() {
		return AssertInteractableResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AssertInteractableResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.AssertInteractableResp)
}

func (p *AssertInteractableResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AssertInteractableResult) GetResult() interface{} {
	return p.Success
}

func getTagsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetTagsReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetTags(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetTagsArgs:
		success, err := handler.(content.ContentService).GetTags(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetTagsResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetTagsArgs() interface{} {
	return &GetTagsArgs{}
}

func newGetTagsResult() interface{} {
	return &GetTagsResult{}
}

type GetTagsArgs struct {
	Req *content.GetTagsReq
}

func (p *GetTagsArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetTagsArgs) Unmarshal(in []byte) error {
	msg := new(content.GetTagsReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetTagsArgs_Req_DEFAULT *content.GetTagsReq

func (p *GetTagsArgs) GetReq() *content.GetTagsReq {
	if !p.IsSetReq() {
		return GetTagsArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetTagsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetTagsArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetTagsResult struct {
	Success *content.GetTagsResp
}

var GetTagsResult_Success_DEFAULT *content.GetTagsResp

func (p *GetTagsResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetTagsResult) Unmarshal(in []byte) error {
	msg := new(content.GetTagsResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetTagsResult) GetSuccess() *content.GetTagsResp {
	if !p.IsSetSuccess() {
		return GetTagsResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetTagsResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetTagsResp)
}

func (p *GetTagsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetTagsResult) GetResult() interface{} {
	return p.Success
}

func getPostsByTagHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(content.GetPostsByTagReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(content.ContentService).GetPostsByTag(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPostsByTagArgs:
		success, err := handler.(content.ContentService).GetPostsByTag(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPostsByTagResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPostsByTagArgs() interface{} {
	return &GetPostsByTagArgs{}
}

func newGetPostsByTagResult() interface{} {
	return &GetPostsByTagResult{}
}

type GetPostsByTagArgs struct {
	Req *content.GetPostsByTagReq
}

func (p *GetPostsByTagArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPostsByTagArgs) Unmarshal(in []byte) error {
	msg := new(content.GetPostsByTagReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPostsByTagArgs_Req_DEFAULT *content.GetPostsByTagReq

func (p *GetPostsByTagArgs) GetReq() *content.GetPostsByTagReq {
	if !p.IsSetReq() {
		return GetPostsByTagArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPostsByTagArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPostsByTagArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPostsByTagResult struct {
	Success *content.GetPostsByTagResp
}

var GetPostsByTagResult_Success_DEFAULT *content.GetPostsByTagResp

func (p *GetPostsByTagResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPostsByTagResult) Unmarshal(in []byte) error {
	msg := new(content.GetPostsByTagResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPostsByTagResult) GetSuccess() *content.GetPostsByTagResp {
	if !p.IsSetSuccess() {
		return GetPostsByTagResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPostsByTagResult) SetSuccess(x interface{}) {
	p.Success = x.(*content.GetPostsByTagResp)
}

func (p *GetPostsByTagResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPostsByTagResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreatePost(ctx context.Context, Req *content.CreatePostReq) (r *content.CreatePostResp, err error) {
	var _args CreatePostArgs
	_args.Req = Req
	var _result CreatePostResult
	if err = p.c.Call(ctx, "CreatePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPost(ctx context.Context, Req *content.GetPostReq) (r *content.GetPostResp, err error) {
	var _args GetPostArgs
	_args.Req = Req
	var _result GetPostResult
	if err = p.c.Call(ctx, "GetPost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePost(ctx context.Context, Req *content.UpdatePostReq) (r *content.UpdatePostResp, err error) {
	var _args UpdatePostArgs
	_args.Req = Req
	var _result UpdatePostResult
	if err = p.c.Call(ctx, "UpdatePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeletePost(ctx context.Context, Req *content.DeletePostReq) (r *content.DeletePostResp, err error) {
	var _args DeletePostArgs
	_args.Req = Req
	var _result DeletePostResult
	if err = p.c.Call(ctx, "DeletePost", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPostList(ctx context.Context, Req *content.GetPostListReq) (r *content.GetPostListResp, err error) {
	var _args GetPostListArgs
	_args.Req = Req
	var _result GetPostListResult
	if err = p.c.Call(ctx, "GetPostList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserPosts(ctx context.Context, Req *content.GetUserPostsReq) (r *content.GetUserPostsResp, err error) {
	var _args GetUserPostsArgs
	_args.Req = Req
	var _result GetUserPostsResult
	if err = p.c.Call(ctx, "GetUserPosts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPostsByIds(ctx context.Context, Req *content.GetPostsByIdsReq) (r *content.GetPostsByIdsResp, err error) {
	var _args GetPostsByIdsArgs
	_args.Req = Req
	var _result GetPostsByIdsResult
	if err = p.c.Call(ctx, "GetPostsByIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateComment(ctx context.Context, Req *content.CreateCommentReq) (r *content.CreateCommentResp, err error) {
	var _args CreateCommentArgs
	_args.Req = Req
	var _result CreateCommentResult
	if err = p.c.Call(ctx, "CreateComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteComment(ctx context.Context, Req *content.DeleteCommentReq) (r *content.DeleteCommentResp, err error) {
	var _args DeleteCommentArgs
	_args.Req = Req
	var _result DeleteCommentResult
	if err = p.c.Call(ctx, "DeleteComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentList(ctx context.Context, Req *content.GetCommentListReq) (r *content.GetCommentListResp, err error) {
	var _args GetCommentListArgs
	_args.Req = Req
	var _result GetCommentListResult
	if err = p.c.Call(ctx, "GetCommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentReplies(ctx context.Context, Req *content.GetCommentRepliesReq) (r *content.GetCommentRepliesResp, err error) {
	var _args GetCommentRepliesArgs
	_args.Req = Req
	var _result GetCommentRepliesResult
	if err = p.c.Call(ctx, "GetCommentReplies", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCommentsByIds(ctx context.Context, Req *content.GetCommentsByIdsReq) (r *content.GetCommentsByIdsResp, err error) {
	var _args GetCommentsByIdsArgs
	_args.Req = Req
	var _result GetCommentsByIdsResult
	if err = p.c.Call(ctx, "GetCommentsByIds", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AssertInteractable(ctx context.Context, Req *content.AssertInteractableReq) (r *content.AssertInteractableResp, err error) {
	var _args AssertInteractableArgs
	_args.Req = Req
	var _result AssertInteractableResult
	if err = p.c.Call(ctx, "AssertInteractable", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTags(ctx context.Context, Req *content.GetTagsReq) (r *content.GetTagsResp, err error) {
	var _args GetTagsArgs
	_args.Req = Req
	var _result GetTagsResult
	if err = p.c.Call(ctx, "GetTags", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPostsByTag(ctx context.Context, Req *content.GetPostsByTagReq) (r *content.GetPostsByTagResp, err error) {
	var _args GetPostsByTagArgs
	_args.Req = Req
	var _result GetPostsByTagResult
	if err = p.c.Call(ctx, "GetPostsByTag", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
