// Code generated by scripts/generate_rpc_adapters.py. DO NOT EDIT.

package behaviorservice

func (c *kBehaviorServiceClient) Close() error {
	return c.kClient.c.(interface{ Close() error }).Close()
}
