// Code generated by Kitex v0.16.2. DO NOT EDIT.

package feedservice

import (
	"context"
	feed "esx/kitex_gen/feed"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetFollowFeed(ctx context.Context, Req *feed.GetFollowFeedReq, callOptions ...callopt.Option) (r *feed.GetFollowFeedResp, err error)
	GetRecommendFeed(ctx context.Context, Req *feed.GetRecommendFeedReq, callOptions ...callopt.Option) (r *feed.GetRecommendFeedResp, err error)
	PushToInbox(ctx context.Context, Req *feed.PushToInboxReq, callOptions ...callopt.Option) (r *feed.PushToInboxResp, err error)
	FanoutPost(ctx context.Context, Req *feed.FanoutPostReq, callOptions ...callopt.Option) (r *feed.FanoutPostResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFeedServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFeedServiceClient struct {
	*kClient
}

func (p *kFeedServiceClient) GetFollowFeed(ctx context.Context, Req *feed.GetFollowFeedReq, callOptions ...callopt.Option) (r *feed.GetFollowFeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowFeed(ctx, Req)
}

func (p *kFeedServiceClient) GetRecommendFeed(ctx context.Context, Req *feed.GetRecommendFeedReq, callOptions ...callopt.Option) (r *feed.GetRecommendFeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRecommendFeed(ctx, Req)
}

func (p *kFeedServiceClient) PushToInbox(ctx context.Context, Req *feed.PushToInboxReq, callOptions ...callopt.Option) (r *feed.PushToInboxResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushToInbox(ctx, Req)
}

func (p *kFeedServiceClient) FanoutPost(ctx context.Context, Req *feed.FanoutPostReq, callOptions ...callopt.Option) (r *feed.FanoutPostResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FanoutPost(ctx, Req)
}
