// Code generated by scripts/generate_rpc_adapters.py. DO NOT EDIT.

package server

import (
	"context"
	"esx/app/search/rpc/internal/logic"
	"esx/app/search/rpc/internal/svc"
	pb "esx/kitex_gen/search"
)

type SearchServiceServer struct{ svcCtx *svc.ServiceContext }

func NewSearchServiceServer(ctx *svc.ServiceContext) *SearchServiceServer {
	return &SearchServiceServer{svcCtx: ctx}
}
func (s *SearchServiceServer) SearchPosts(ctx context.Context, req *pb.SearchPostsReq) (*pb.SearchPostsResp, error) {
	return logic.NewSearchPostsLogic(ctx, s.svcCtx).SearchPosts(req)
}
func (s *SearchServiceServer) SearchUsers(ctx context.Context, req *pb.SearchUsersReq) (*pb.SearchUsersResp, error) {
	return logic.NewSearchUsersLogic(ctx, s.svcCtx).SearchUsers(req)
}
func (s *SearchServiceServer) SearchTags(ctx context.Context, req *pb.SearchTagsReq) (*pb.SearchTagsResp, error) {
	return logic.NewSearchTagsLogic(ctx, s.svcCtx).SearchTags(req)
}
func (s *SearchServiceServer) Search(ctx context.Context, req *pb.SearchReq) (*pb.SearchResp, error) {
	return logic.NewSearchLogic(ctx, s.svcCtx).Search(req)
}
func (s *SearchServiceServer) GetHotSearches(ctx context.Context, req *pb.GetHotSearchesReq) (*pb.GetHotSearchesResp, error) {
	return logic.NewGetHotSearchesLogic(ctx, s.svcCtx).GetHotSearches(req)
}
