// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/assistant/assistant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssistantService_GetThread_FullMethodName               = "/assistant.AssistantService/GetThread"
	AssistantService_ListMessages_FullMethodName            = "/assistant.AssistantService/ListMessages"
	AssistantService_PostMessage_FullMethodName             = "/assistant.AssistantService/PostMessage"
	AssistantService_CreateSession_FullMethodName           = "/assistant.AssistantService/CreateSession"
	AssistantService_MarkThreadRead_FullMethodName          = "/assistant.AssistantService/MarkThreadRead"
	AssistantService_DeleteHistory_FullMethodName           = "/assistant.AssistantService/DeleteHistory"
	AssistantService_SubscribeRunEvents_FullMethodName      = "/assistant.AssistantService/SubscribeRunEvents"
	AssistantService_CancelRun_FullMethodName               = "/assistant.AssistantService/CancelRun"
	AssistantService_RevokeConsent_FullMethodName           = "/assistant.AssistantService/RevokeConsent"
	AssistantService_ConfirmRunTool_FullMethodName          = "/assistant.AssistantService/ConfirmRunTool"
	AssistantService_ListMemory_FullMethodName              = "/assistant.AssistantService/ListMemory"
	AssistantService_AddMemory_FullMethodName               = "/assistant.AssistantService/AddMemory"
	AssistantService_ReplaceMemory_FullMethodName           = "/assistant.AssistantService/ReplaceMemory"
	AssistantService_RemoveMemory_FullMethodName            = "/assistant.AssistantService/RemoveMemory"
	AssistantService_BatchMemory_FullMethodName             = "/assistant.AssistantService/BatchMemory"
	AssistantService_UndoMemoryChange_FullMethodName        = "/assistant.AssistantService/UndoMemoryChange"
	AssistantService_ListWatchTasks_FullMethodName          = "/assistant.AssistantService/ListWatchTasks"
	AssistantService_CreateWatchTask_FullMethodName         = "/assistant.AssistantService/CreateWatchTask"
	AssistantService_UpdateWatchTask_FullMethodName         = "/assistant.AssistantService/UpdateWatchTask"
	AssistantService_DeleteWatchTask_FullMethodName         = "/assistant.AssistantService/DeleteWatchTask"
	AssistantService_SubmitRecommendFeedback_FullMethodName = "/assistant.AssistantService/SubmitRecommendFeedback"
)

// AssistantServiceClient is the client API for AssistantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistantServiceClient interface {
	GetThread(ctx context.Context, in *GetThreadReq, opts ...grpc.CallOption) (*GetThreadResp, error)
	ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error)
	PostMessage(ctx context.Context, in *PostMessageReq, opts ...grpc.CallOption) (*PostMessageResp, error)
	CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error)
	MarkThreadRead(ctx context.Context, in *MarkThreadReadReq, opts ...grpc.CallOption) (*MarkThreadReadResp, error)
	DeleteHistory(ctx context.Context, in *DeleteHistoryReq, opts ...grpc.CallOption) (*DeleteHistoryResp, error)
	SubscribeRunEvents(ctx context.Context, in *SubscribeRunEventsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
	CancelRun(ctx context.Context, in *CancelRunReq, opts ...grpc.CallOption) (*CancelRunResp, error)
	RevokeConsent(ctx context.Context, in *RevokeConsentReq, opts ...grpc.CallOption) (*RevokeConsentResp, error)
	ConfirmRunTool(ctx context.Context, in *ConfirmRunToolReq, opts ...grpc.CallOption) (*ConfirmRunToolResp, error)
	ListMemory(ctx context.Context, in *ListMemoryReq, opts ...grpc.CallOption) (*ListMemoryResp, error)
	AddMemory(ctx context.Context, in *AddMemoryReq, opts ...grpc.CallOption) (*AddMemoryResp, error)
	ReplaceMemory(ctx context.Context, in *ReplaceMemoryReq, opts ...grpc.CallOption) (*ReplaceMemoryResp, error)
	RemoveMemory(ctx context.Context, in *RemoveMemoryReq, opts ...grpc.CallOption) (*RemoveMemoryResp, error)
	BatchMemory(ctx context.Context, in *BatchMemoryReq, opts ...grpc.CallOption) (*BatchMemoryResp, error)
	UndoMemoryChange(ctx context.Context, in *UndoMemoryChangeReq, opts ...grpc.CallOption) (*UndoMemoryChangeResp, error)
	ListWatchTasks(ctx context.Context, in *ListWatchTasksReq, opts ...grpc.CallOption) (*ListWatchTasksResp, error)
	CreateWatchTask(ctx context.Context, in *CreateWatchTaskReq, opts ...grpc.CallOption) (*CreateWatchTaskResp, error)
	UpdateWatchTask(ctx context.Context, in *UpdateWatchTaskReq, opts ...grpc.CallOption) (*UpdateWatchTaskResp, error)
	DeleteWatchTask(ctx context.Context, in *DeleteWatchTaskReq, opts ...grpc.CallOption) (*DeleteWatchTaskResp, error)
	SubmitRecommendFeedback(ctx context.Context, in *SubmitRecommendFeedbackReq, opts ...grpc.CallOption) (*SubmitRecommendFeedbackResp, error)
}

type assistantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistantServiceClient(cc grpc.ClientConnInterface) AssistantServiceClient {
	return &assistantServiceClient{cc}
}

func (c *assistantServiceClient) GetThread(ctx context.Context, in *GetThreadReq, opts ...grpc.CallOption) (*GetThreadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThreadResp)
	err := c.cc.Invoke(ctx, AssistantService_GetThread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResp)
	err := c.cc.Invoke(ctx, AssistantService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) PostMessage(ctx context.Context, in *PostMessageReq, opts ...grpc.CallOption) (*PostMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostMessageResp)
	err := c.cc.Invoke(ctx, AssistantService_PostMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) CreateSession(ctx context.Context, in *CreateSessionReq, opts ...grpc.CallOption) (*CreateSessionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResp)
	err := c.cc.Invoke(ctx, AssistantService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) MarkThreadRead(ctx context.Context, in *MarkThreadReadReq, opts ...grpc.CallOption) (*MarkThreadReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkThreadReadResp)
	err := c.cc.Invoke(ctx, AssistantService_MarkThreadRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) DeleteHistory(ctx context.Context, in *DeleteHistoryReq, opts ...grpc.CallOption) (*DeleteHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHistoryResp)
	err := c.cc.Invoke(ctx, AssistantService_DeleteHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) SubscribeRunEvents(ctx context.Context, in *SubscribeRunEventsReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AssistantService_ServiceDesc.Streams[0], AssistantService_SubscribeRunEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRunEventsReq, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssistantService_SubscribeRunEventsClient = grpc.ServerStreamingClient[RunEvent]

func (c *assistantServiceClient) CancelRun(ctx context.Context, in *CancelRunReq, opts ...grpc.CallOption) (*CancelRunResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResp)
	err := c.cc.Invoke(ctx, AssistantService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) RevokeConsent(ctx context.Context, in *RevokeConsentReq, opts ...grpc.CallOption) (*RevokeConsentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeConsentResp)
	err := c.cc.Invoke(ctx, AssistantService_RevokeConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ConfirmRunTool(ctx context.Context, in *ConfirmRunToolReq, opts ...grpc.CallOption) (*ConfirmRunToolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmRunToolResp)
	err := c.cc.Invoke(ctx, AssistantService_ConfirmRunTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ListMemory(ctx context.Context, in *ListMemoryReq, opts ...grpc.CallOption) (*ListMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_ListMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) AddMemory(ctx context.Context, in *AddMemoryReq, opts ...grpc.CallOption) (*AddMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_AddMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ReplaceMemory(ctx context.Context, in *ReplaceMemoryReq, opts ...grpc.CallOption) (*ReplaceMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_ReplaceMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) RemoveMemory(ctx context.Context, in *RemoveMemoryReq, opts ...grpc.CallOption) (*RemoveMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_RemoveMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) BatchMemory(ctx context.Context, in *BatchMemoryReq, opts ...grpc.CallOption) (*BatchMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_BatchMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) UndoMemoryChange(ctx context.Context, in *UndoMemoryChangeReq, opts ...grpc.CallOption) (*UndoMemoryChangeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndoMemoryChangeResp)
	err := c.cc.Invoke(ctx, AssistantService_UndoMemoryChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ListWatchTasks(ctx context.Context, in *ListWatchTasksReq, opts ...grpc.CallOption) (*ListWatchTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchTasksResp)
	err := c.cc.Invoke(ctx, AssistantService_ListWatchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) CreateWatchTask(ctx context.Context, in *CreateWatchTaskReq, opts ...grpc.CallOption) (*CreateWatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWatchTaskResp)
	err := c.cc.Invoke(ctx, AssistantService_CreateWatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) UpdateWatchTask(ctx context.Context, in *UpdateWatchTaskReq, opts ...grpc.CallOption) (*UpdateWatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWatchTaskResp)
	err := c.cc.Invoke(ctx, AssistantService_UpdateWatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) DeleteWatchTask(ctx context.Context, in *DeleteWatchTaskReq, opts ...grpc.CallOption) (*DeleteWatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWatchTaskResp)
	err := c.cc.Invoke(ctx, AssistantService_DeleteWatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) SubmitRecommendFeedback(ctx context.Context, in *SubmitRecommendFeedbackReq, opts ...grpc.CallOption) (*SubmitRecommendFeedbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRecommendFeedbackResp)
	err := c.cc.Invoke(ctx, AssistantService_SubmitRecommendFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistantServiceServer is the server API for AssistantService service.
// All implementations must embed UnimplementedAssistantServiceServer
// for forward compatibility.
type AssistantServiceServer interface {
	GetThread(context.Context, *GetThreadReq) (*GetThreadResp, error)
	ListMessages(context.Context, *ListMessagesReq) (*ListMessagesResp, error)
	PostMessage(context.Context, *PostMessageReq) (*PostMessageResp, error)
	CreateSession(context.Context, *CreateSessionReq) (*CreateSessionResp, error)
	MarkThreadRead(context.Context, *MarkThreadReadReq) (*MarkThreadReadResp, error)
	DeleteHistory(context.Context, *DeleteHistoryReq) (*DeleteHistoryResp, error)
	SubscribeRunEvents(*SubscribeRunEventsReq, grpc.ServerStreamingServer[RunEvent]) error
	CancelRun(context.Context, *CancelRunReq) (*CancelRunResp, error)
	RevokeConsent(context.Context, *RevokeConsentReq) (*RevokeConsentResp, error)
	ConfirmRunTool(context.Context, *ConfirmRunToolReq) (*ConfirmRunToolResp, error)
	ListMemory(context.Context, *ListMemoryReq) (*ListMemoryResp, error)
	AddMemory(context.Context, *AddMemoryReq) (*AddMemoryResp, error)
	ReplaceMemory(context.Context, *ReplaceMemoryReq) (*ReplaceMemoryResp, error)
	RemoveMemory(context.Context, *RemoveMemoryReq) (*RemoveMemoryResp, error)
	BatchMemory(context.Context, *BatchMemoryReq) (*BatchMemoryResp, error)
	UndoMemoryChange(context.Context, *UndoMemoryChangeReq) (*UndoMemoryChangeResp, error)
	ListWatchTasks(context.Context, *ListWatchTasksReq) (*ListWatchTasksResp, error)
	CreateWatchTask(context.Context, *CreateWatchTaskReq) (*CreateWatchTaskResp, error)
	UpdateWatchTask(context.Context, *UpdateWatchTaskReq) (*UpdateWatchTaskResp, error)
	DeleteWatchTask(context.Context, *DeleteWatchTaskReq) (*DeleteWatchTaskResp, error)
	SubmitRecommendFeedback(context.Context, *SubmitRecommendFeedbackReq) (*SubmitRecommendFeedbackResp, error)
	mustEmbedUnimplementedAssistantServiceServer()
}

// UnimplementedAssistantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssistantServiceServer struct{}

func (UnimplementedAssistantServiceServer) GetThread(context.Context, *GetThreadReq) (*GetThreadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThread not implemented")
}
func (UnimplementedAssistantServiceServer) ListMessages(context.Context, *ListMessagesReq) (*ListMessagesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedAssistantServiceServer) PostMessage(context.Context, *PostMessageReq) (*PostMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedAssistantServiceServer) CreateSession(context.Context, *CreateSessionReq) (*CreateSessionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAssistantServiceServer) MarkThreadRead(context.Context, *MarkThreadReadReq) (*MarkThreadReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkThreadRead not implemented")
}
func (UnimplementedAssistantServiceServer) DeleteHistory(context.Context, *DeleteHistoryReq) (*DeleteHistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHistory not implemented")
}
func (UnimplementedAssistantServiceServer) SubscribeRunEvents(*SubscribeRunEventsReq, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRunEvents not implemented")
}
func (UnimplementedAssistantServiceServer) CancelRun(context.Context, *CancelRunReq) (*CancelRunResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedAssistantServiceServer) RevokeConsent(context.Context, *RevokeConsentReq) (*RevokeConsentResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeConsent not implemented")
}
func (UnimplementedAssistantServiceServer) ConfirmRunTool(context.Context, *ConfirmRunToolReq) (*ConfirmRunToolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmRunTool not implemented")
}
func (UnimplementedAssistantServiceServer) ListMemory(context.Context, *ListMemoryReq) (*ListMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemory not implemented")
}
func (UnimplementedAssistantServiceServer) AddMemory(context.Context, *AddMemoryReq) (*AddMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMemory not implemented")
}
func (UnimplementedAssistantServiceServer) ReplaceMemory(context.Context, *ReplaceMemoryReq) (*ReplaceMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceMemory not implemented")
}
func (UnimplementedAssistantServiceServer) RemoveMemory(context.Context, *RemoveMemoryReq) (*RemoveMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMemory not implemented")
}
func (UnimplementedAssistantServiceServer) BatchMemory(context.Context, *BatchMemoryReq) (*BatchMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchMemory not implemented")
}
func (UnimplementedAssistantServiceServer) UndoMemoryChange(context.Context, *UndoMemoryChangeReq) (*UndoMemoryChangeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UndoMemoryChange not implemented")
}
func (UnimplementedAssistantServiceServer) ListWatchTasks(context.Context, *ListWatchTasksReq) (*ListWatchTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchTasks not implemented")
}
func (UnimplementedAssistantServiceServer) CreateWatchTask(context.Context, *CreateWatchTaskReq) (*CreateWatchTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWatchTask not implemented")
}
func (UnimplementedAssistantServiceServer) UpdateWatchTask(context.Context, *UpdateWatchTaskReq) (*UpdateWatchTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWatchTask not implemented")
}
func (UnimplementedAssistantServiceServer) DeleteWatchTask(context.Context, *DeleteWatchTaskReq) (*DeleteWatchTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWatchTask not implemented")
}
func (UnimplementedAssistantServiceServer) SubmitRecommendFeedback(context.Context, *SubmitRecommendFeedbackReq) (*SubmitRecommendFeedbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRecommendFeedback not implemented")
}
func (UnimplementedAssistantServiceServer) mustEmbedUnimplementedAssistantServiceServer() {}
func (UnimplementedAssistantServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssistantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistantServiceServer will
// result in compilation errors.
type UnsafeAssistantServiceServer interface {
	mustEmbedUnimplementedAssistantServiceServer()
}

func RegisterAssistantServiceServer(s grpc.ServiceRegistrar, srv AssistantServiceServer) {
	// If the following call panics, it indicates UnimplementedAssistantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssistantService_ServiceDesc, srv)
}

func _AssistantService_GetThread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThreadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).GetThread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_GetThread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).GetThread(ctx, req.(*GetThreadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ListMessages(ctx, req.(*ListMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).PostMessage(ctx, req.(*PostMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).CreateSession(ctx, req.(*CreateSessionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_MarkThreadRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkThreadReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).MarkThreadRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_MarkThreadRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).MarkThreadRead(ctx, req.(*MarkThreadReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_DeleteHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).DeleteHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_DeleteHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).DeleteHistory(ctx, req.(*DeleteHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_SubscribeRunEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRunEventsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssistantServiceServer).SubscribeRunEvents(m, &grpc.GenericServerStream[SubscribeRunEventsReq, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssistantService_SubscribeRunEventsServer = grpc.ServerStreamingServer[RunEvent]

func _AssistantService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).CancelRun(ctx, req.(*CancelRunReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_RevokeConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeConsentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).RevokeConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_RevokeConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).RevokeConsent(ctx, req.(*RevokeConsentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ConfirmRunTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRunToolReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ConfirmRunTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ConfirmRunTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ConfirmRunTool(ctx, req.(*ConfirmRunToolReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ListMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ListMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ListMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ListMemory(ctx, req.(*ListMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_AddMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).AddMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_AddMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).AddMemory(ctx, req.(*AddMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ReplaceMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ReplaceMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ReplaceMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ReplaceMemory(ctx, req.(*ReplaceMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_RemoveMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).RemoveMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_RemoveMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).RemoveMemory(ctx, req.(*RemoveMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_BatchMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).BatchMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_BatchMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).BatchMemory(ctx, req.(*BatchMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_UndoMemoryChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndoMemoryChangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).UndoMemoryChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_UndoMemoryChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).UndoMemoryChange(ctx, req.(*UndoMemoryChangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ListWatchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ListWatchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ListWatchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ListWatchTasks(ctx, req.(*ListWatchTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_CreateWatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).CreateWatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_CreateWatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).CreateWatchTask(ctx, req.(*CreateWatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_UpdateWatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).UpdateWatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_UpdateWatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).UpdateWatchTask(ctx, req.(*UpdateWatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_DeleteWatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).DeleteWatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_DeleteWatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).DeleteWatchTask(ctx, req.(*DeleteWatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_SubmitRecommendFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRecommendFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).SubmitRecommendFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_SubmitRecommendFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).SubmitRecommendFeedback(ctx, req.(*SubmitRecommendFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AssistantService_ServiceDesc is the grpc.ServiceDesc for AssistantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssistantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.AssistantService",
	HandlerType: (*AssistantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThread",
			Handler:    _AssistantService_GetThread_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _AssistantService_ListMessages_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _AssistantService_PostMessage_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _AssistantService_CreateSession_Handler,
		},
		{
			MethodName: "MarkThreadRead",
			Handler:    _AssistantService_MarkThreadRead_Handler,
		},
		{
			MethodName: "DeleteHistory",
			Handler:    _AssistantService_DeleteHistory_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _AssistantService_CancelRun_Handler,
		},
		{
			MethodName: "RevokeConsent",
			Handler:    _AssistantService_RevokeConsent_Handler,
		},
		{
			MethodName: "ConfirmRunTool",
			Handler:    _AssistantService_ConfirmRunTool_Handler,
		},
		{
			MethodName: "ListMemory",
			Handler:    _AssistantService_ListMemory_Handler,
		},
		{
			MethodName: "AddMemory",
			Handler:    _AssistantService_AddMemory_Handler,
		},
		{
			MethodName: "ReplaceMemory",
			Handler:    _AssistantService_ReplaceMemory_Handler,
		},
		{
			MethodName: "RemoveMemory",
			Handler:    _AssistantService_RemoveMemory_Handler,
		},
		{
			MethodName: "BatchMemory",
			Handler:    _AssistantService_BatchMemory_Handler,
		},
		{
			MethodName: "UndoMemoryChange",
			Handler:    _AssistantService_UndoMemoryChange_Handler,
		},
		{
			MethodName: "ListWatchTasks",
			Handler:    _AssistantService_ListWatchTasks_Handler,
		},
		{
			MethodName: "CreateWatchTask",
			Handler:    _AssistantService_CreateWatchTask_Handler,
		},
		{
			MethodName: "UpdateWatchTask",
			Handler:    _AssistantService_UpdateWatchTask_Handler,
		},
		{
			MethodName: "DeleteWatchTask",
			Handler:    _AssistantService_DeleteWatchTask_Handler,
		},
		{
			MethodName: "SubmitRecommendFeedback",
			Handler:    _AssistantService_SubmitRecommendFeedback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRunEvents",
			Handler:       _AssistantService_SubscribeRunEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/assistant/assistant.proto",
}
