// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/assistant/assistant.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssistantService_Chat_FullMethodName                    = "/assistant.AssistantService/Chat"
	AssistantService_ConfirmToolCall_FullMethodName         = "/assistant.AssistantService/ConfirmToolCall"
	AssistantService_ListMemory_FullMethodName              = "/assistant.AssistantService/ListMemory"
	AssistantService_UpdateMemory_FullMethodName            = "/assistant.AssistantService/UpdateMemory"
	AssistantService_DeleteMemory_FullMethodName            = "/assistant.AssistantService/DeleteMemory"
	AssistantService_ListWatchTasks_FullMethodName          = "/assistant.AssistantService/ListWatchTasks"
	AssistantService_CreateWatchTask_FullMethodName         = "/assistant.AssistantService/CreateWatchTask"
	AssistantService_UpdateWatchTask_FullMethodName         = "/assistant.AssistantService/UpdateWatchTask"
	AssistantService_DeleteWatchTask_FullMethodName         = "/assistant.AssistantService/DeleteWatchTask"
	AssistantService_ListWatchHits_FullMethodName           = "/assistant.AssistantService/ListWatchHits"
	AssistantService_MarkWatchHitsRead_FullMethodName       = "/assistant.AssistantService/MarkWatchHitsRead"
	AssistantService_SubmitRecommendFeedback_FullMethodName = "/assistant.AssistantService/SubmitRecommendFeedback"
)

// AssistantServiceClient is the client API for AssistantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistantServiceClient interface {
	Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// Agent 模式高危操作确认回调（AGNT-020~022）
	ConfirmToolCall(ctx context.Context, in *ConfirmToolCallReq, opts ...grpc.CallOption) (*ConfirmToolCallResp, error)
	ListMemory(ctx context.Context, in *ListMemoryReq, opts ...grpc.CallOption) (*ListMemoryResp, error)
	UpdateMemory(ctx context.Context, in *UpdateMemoryReq, opts ...grpc.CallOption) (*UpdateMemoryResp, error)
	DeleteMemory(ctx context.Context, in *DeleteMemoryReq, opts ...grpc.CallOption) (*DeleteMemoryResp, error)
	ListWatchTasks(ctx context.Context, in *ListWatchTasksReq, opts ...grpc.CallOption) (*ListWatchTasksResp, error)
	CreateWatchTask(ctx context.Context, in *CreateWatchTaskReq, opts ...grpc.CallOption) (*CreateWatchTaskResp, error)
	UpdateWatchTask(ctx context.Context, in *UpdateWatchTaskReq, opts ...grpc.CallOption) (*UpdateWatchTaskResp, error)
	DeleteWatchTask(ctx context.Context, in *DeleteWatchTaskReq, opts ...grpc.CallOption) (*DeleteWatchTaskResp, error)
	ListWatchHits(ctx context.Context, in *ListWatchHitsReq, opts ...grpc.CallOption) (*ListWatchHitsResp, error)
	MarkWatchHitsRead(ctx context.Context, in *MarkWatchHitsReadReq, opts ...grpc.CallOption) (*MarkWatchHitsReadResp, error)
	SubmitRecommendFeedback(ctx context.Context, in *SubmitRecommendFeedbackReq, opts ...grpc.CallOption) (*SubmitRecommendFeedbackResp, error)
}

type assistantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistantServiceClient(cc grpc.ClientConnInterface) AssistantServiceClient {
	return &assistantServiceClient{cc}
}

func (c *assistantServiceClient) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AssistantService_ServiceDesc.Streams[0], AssistantService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatReq, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssistantService_ChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *assistantServiceClient) ConfirmToolCall(ctx context.Context, in *ConfirmToolCallReq, opts ...grpc.CallOption) (*ConfirmToolCallResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmToolCallResp)
	err := c.cc.Invoke(ctx, AssistantService_ConfirmToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ListMemory(ctx context.Context, in *ListMemoryReq, opts ...grpc.CallOption) (*ListMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_ListMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) UpdateMemory(ctx context.Context, in *UpdateMemoryReq, opts ...grpc.CallOption) (*UpdateMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_UpdateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) DeleteMemory(ctx context.Context, in *DeleteMemoryReq, opts ...grpc.CallOption) (*DeleteMemoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMemoryResp)
	err := c.cc.Invoke(ctx, AssistantService_DeleteMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ListWatchTasks(ctx context.Context, in *ListWatchTasksReq, opts ...grpc.CallOption) (*ListWatchTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchTasksResp)
	err := c.cc.Invoke(ctx, AssistantService_ListWatchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) CreateWatchTask(ctx context.Context, in *CreateWatchTaskReq, opts ...grpc.CallOption) (*CreateWatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWatchTaskResp)
	err := c.cc.Invoke(ctx, AssistantService_CreateWatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) UpdateWatchTask(ctx context.Context, in *UpdateWatchTaskReq, opts ...grpc.CallOption) (*UpdateWatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWatchTaskResp)
	err := c.cc.Invoke(ctx, AssistantService_UpdateWatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) DeleteWatchTask(ctx context.Context, in *DeleteWatchTaskReq, opts ...grpc.CallOption) (*DeleteWatchTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWatchTaskResp)
	err := c.cc.Invoke(ctx, AssistantService_DeleteWatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) ListWatchHits(ctx context.Context, in *ListWatchHitsReq, opts ...grpc.CallOption) (*ListWatchHitsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchHitsResp)
	err := c.cc.Invoke(ctx, AssistantService_ListWatchHits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) MarkWatchHitsRead(ctx context.Context, in *MarkWatchHitsReadReq, opts ...grpc.CallOption) (*MarkWatchHitsReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkWatchHitsReadResp)
	err := c.cc.Invoke(ctx, AssistantService_MarkWatchHitsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) SubmitRecommendFeedback(ctx context.Context, in *SubmitRecommendFeedbackReq, opts ...grpc.CallOption) (*SubmitRecommendFeedbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRecommendFeedbackResp)
	err := c.cc.Invoke(ctx, AssistantService_SubmitRecommendFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistantServiceServer is the server API for AssistantService service.
// All implementations must embed UnimplementedAssistantServiceServer
// for forward compatibility.
type AssistantServiceServer interface {
	Chat(*ChatReq, grpc.ServerStreamingServer[ChatEvent]) error
	// Agent 模式高危操作确认回调（AGNT-020~022）
	ConfirmToolCall(context.Context, *ConfirmToolCallReq) (*ConfirmToolCallResp, error)
	ListMemory(context.Context, *ListMemoryReq) (*ListMemoryResp, error)
	UpdateMemory(context.Context, *UpdateMemoryReq) (*UpdateMemoryResp, error)
	DeleteMemory(context.Context, *DeleteMemoryReq) (*DeleteMemoryResp, error)
	ListWatchTasks(context.Context, *ListWatchTasksReq) (*ListWatchTasksResp, error)
	CreateWatchTask(context.Context, *CreateWatchTaskReq) (*CreateWatchTaskResp, error)
	UpdateWatchTask(context.Context, *UpdateWatchTaskReq) (*UpdateWatchTaskResp, error)
	DeleteWatchTask(context.Context, *DeleteWatchTaskReq) (*DeleteWatchTaskResp, error)
	ListWatchHits(context.Context, *ListWatchHitsReq) (*ListWatchHitsResp, error)
	MarkWatchHitsRead(context.Context, *MarkWatchHitsReadReq) (*MarkWatchHitsReadResp, error)
	SubmitRecommendFeedback(context.Context, *SubmitRecommendFeedbackReq) (*SubmitRecommendFeedbackResp, error)
	mustEmbedUnimplementedAssistantServiceServer()
}

// UnimplementedAssistantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssistantServiceServer struct{}

func (UnimplementedAssistantServiceServer) Chat(*ChatReq, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAssistantServiceServer) ConfirmToolCall(context.Context, *ConfirmToolCallReq) (*ConfirmToolCallResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmToolCall not implemented")
}
func (UnimplementedAssistantServiceServer) ListMemory(context.Context, *ListMemoryReq) (*ListMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemory not implemented")
}
func (UnimplementedAssistantServiceServer) UpdateMemory(context.Context, *UpdateMemoryReq) (*UpdateMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMemory not implemented")
}
func (UnimplementedAssistantServiceServer) DeleteMemory(context.Context, *DeleteMemoryReq) (*DeleteMemoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMemory not implemented")
}
func (UnimplementedAssistantServiceServer) ListWatchTasks(context.Context, *ListWatchTasksReq) (*ListWatchTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchTasks not implemented")
}
func (UnimplementedAssistantServiceServer) CreateWatchTask(context.Context, *CreateWatchTaskReq) (*CreateWatchTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWatchTask not implemented")
}
func (UnimplementedAssistantServiceServer) UpdateWatchTask(context.Context, *UpdateWatchTaskReq) (*UpdateWatchTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWatchTask not implemented")
}
func (UnimplementedAssistantServiceServer) DeleteWatchTask(context.Context, *DeleteWatchTaskReq) (*DeleteWatchTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWatchTask not implemented")
}
func (UnimplementedAssistantServiceServer) ListWatchHits(context.Context, *ListWatchHitsReq) (*ListWatchHitsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchHits not implemented")
}
func (UnimplementedAssistantServiceServer) MarkWatchHitsRead(context.Context, *MarkWatchHitsReadReq) (*MarkWatchHitsReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkWatchHitsRead not implemented")
}
func (UnimplementedAssistantServiceServer) SubmitRecommendFeedback(context.Context, *SubmitRecommendFeedbackReq) (*SubmitRecommendFeedbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitRecommendFeedback not implemented")
}
func (UnimplementedAssistantServiceServer) mustEmbedUnimplementedAssistantServiceServer() {}
func (UnimplementedAssistantServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssistantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistantServiceServer will
// result in compilation errors.
type UnsafeAssistantServiceServer interface {
	mustEmbedUnimplementedAssistantServiceServer()
}

func RegisterAssistantServiceServer(s grpc.ServiceRegistrar, srv AssistantServiceServer) {
	// If the following call panics, it indicates UnimplementedAssistantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssistantService_ServiceDesc, srv)
}

func _AssistantService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssistantServiceServer).Chat(m, &grpc.GenericServerStream[ChatReq, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AssistantService_ChatServer = grpc.ServerStreamingServer[ChatEvent]

func _AssistantService_ConfirmToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmToolCallReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ConfirmToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ConfirmToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ConfirmToolCall(ctx, req.(*ConfirmToolCallReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ListMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ListMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ListMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ListMemory(ctx, req.(*ListMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_UpdateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).UpdateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_UpdateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).UpdateMemory(ctx, req.(*UpdateMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_DeleteMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).DeleteMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_DeleteMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).DeleteMemory(ctx, req.(*DeleteMemoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ListWatchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ListWatchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ListWatchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ListWatchTasks(ctx, req.(*ListWatchTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_CreateWatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).CreateWatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_CreateWatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).CreateWatchTask(ctx, req.(*CreateWatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_UpdateWatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).UpdateWatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_UpdateWatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).UpdateWatchTask(ctx, req.(*UpdateWatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_DeleteWatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).DeleteWatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_DeleteWatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).DeleteWatchTask(ctx, req.(*DeleteWatchTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_ListWatchHits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchHitsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).ListWatchHits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_ListWatchHits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).ListWatchHits(ctx, req.(*ListWatchHitsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_MarkWatchHitsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkWatchHitsReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).MarkWatchHitsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_MarkWatchHitsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).MarkWatchHitsRead(ctx, req.(*MarkWatchHitsReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_SubmitRecommendFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRecommendFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).SubmitRecommendFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_SubmitRecommendFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).SubmitRecommendFeedback(ctx, req.(*SubmitRecommendFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AssistantService_ServiceDesc is the grpc.ServiceDesc for AssistantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssistantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assistant.AssistantService",
	HandlerType: (*AssistantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmToolCall",
			Handler:    _AssistantService_ConfirmToolCall_Handler,
		},
		{
			MethodName: "ListMemory",
			Handler:    _AssistantService_ListMemory_Handler,
		},
		{
			MethodName: "UpdateMemory",
			Handler:    _AssistantService_UpdateMemory_Handler,
		},
		{
			MethodName: "DeleteMemory",
			Handler:    _AssistantService_DeleteMemory_Handler,
		},
		{
			MethodName: "ListWatchTasks",
			Handler:    _AssistantService_ListWatchTasks_Handler,
		},
		{
			MethodName: "CreateWatchTask",
			Handler:    _AssistantService_CreateWatchTask_Handler,
		},
		{
			MethodName: "UpdateWatchTask",
			Handler:    _AssistantService_UpdateWatchTask_Handler,
		},
		{
			MethodName: "DeleteWatchTask",
			Handler:    _AssistantService_DeleteWatchTask_Handler,
		},
		{
			MethodName: "ListWatchHits",
			Handler:    _AssistantService_ListWatchHits_Handler,
		},
		{
			MethodName: "MarkWatchHitsRead",
			Handler:    _AssistantService_MarkWatchHitsRead_Handler,
		},
		{
			MethodName: "SubmitRecommendFeedback",
			Handler:    _AssistantService_SubmitRecommendFeedback_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AssistantService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/assistant/assistant.proto",
}
