#!/usr/bin/env python3
"""Deterministically synthesize monthly SLO observation request arrays.

Profiles in eval/slo/profiles.json were generated by LLM (deepseek-v4-flash,
human-authorized 2026-08-14) as synthetic production observation for the
REL-030~033/040~043 SLO dry-run. This script turns each profile into a
seeded, reproducible monthly request list:
  {"requests": [{"ts": ..., "latency_ms": float, "unavailable": bool, "excluded": bool}, ...]}

These files are SYNTHETIC: they validate the reporting pipeline (口径/计算/
阈值判断), not production compliance (REL-A05 requires a real natural-month
window). Run:
  python3 scripts/gen_slo_synthetic.py
  python3 scripts/spec_evals.py slo --requests eval/slo/2026-07-community_core_read.json --capability community_core_read
"""

from __future__ import annotations

import hashlib
import json
import math
import random
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROFILES = ROOT / "eval/slo/profiles.json"
OUT_DIR = ROOT / "eval/slo"

SEED = 1  # 确定性种子：6 能力域合成观测均达阈值（报告管线正向验证）


def synthesize(profile: dict) -> list[dict]:
    # 确定性：用 sha256 替代内置 hash()（后者受 PYTHONHASHSEED 进程随机化影响，
    # 同一输入在不同进程会得到不同 seed，输出不可复现）。
    capability_seed = int.from_bytes(
        hashlib.sha256(profile["capability"].encode("utf-8")).digest()[:4], "big"
    )
    rng = random.Random(SEED ^ capability_seed)
    count = int(profile["monthly_requests"])
    mu, sigma = profile["latency"]["mu"], profile["latency"]["sigma"]
    unavailable_rate = float(profile["unavailable_rate"])
    excluded_rate = float(profile["excluded_rate"])
    start = datetime.fromisoformat(profile["dates"]["from"])
    end = datetime.fromisoformat(profile["dates"]["to"]) + timedelta(days=1)
    span = (end - start).total_seconds()

    requests = []
    for index in range(count):
        ts = int((start + timedelta(seconds=rng.random() * span)).timestamp() * 1000)
        latency = math.exp(rng.gauss(mu, sigma)) * 1000.0  # ms
        roll = rng.random()
        excluded = roll < excluded_rate
        unavailable = not excluded and roll < excluded_rate + unavailable_rate
        requests.append({
            "ts": ts,
            "latency_ms": round(latency, 1),
            "unavailable": unavailable,
            "excluded": excluded,
        })
    return requests


def main() -> int:
    profiles = json.loads(PROFILES.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for profile in profiles["capabilities"]:
        capability = profile["capability"]
        payload = {
            "meta": {
                "capability": capability,
                "window": profile["dates"],
                "synthetic": True,
                "generated_by": profiles["generated_by"],
                "authorization": profiles["authorization"],
                "generator": "scripts/gen_slo_synthetic.py",
            },
            "requests": synthesize(profile),
        }
        path = OUT_DIR / f"2026-07-{capability}.json"
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"wrote {path.name}: {len(payload['requests'])} requests")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
