// Code generated by scripts/generate_rpc_adapters.py. DO NOT EDIT.

package server

import (
	"context"
	"esx/app/recommend/rpc/internal/logic"
	"esx/app/recommend/rpc/internal/svc"
	pb "esx/kitex_gen/recommend"
)

type RecommendServiceServer struct{ svcCtx *svc.ServiceContext }

func NewRecommendServiceServer(ctx *svc.ServiceContext) *RecommendServiceServer {
	return &RecommendServiceServer{svcCtx: ctx}
}
func (s *RecommendServiceServer) GetRecommendPosts(ctx context.Context, req *pb.GetRecommendPostsReq) (*pb.GetRecommendPostsResp, error) {
	return logic.NewGetRecommendPostsLogic(ctx, s.svcCtx).GetRecommendPosts(req)
}
func (s *RecommendServiceServer) GetSimilarPosts(ctx context.Context, req *pb.GetSimilarPostsReq) (*pb.GetSimilarPostsResp, error) {
	return logic.NewGetSimilarPostsLogic(ctx, s.svcCtx).GetSimilarPosts(req)
}
func (s *RecommendServiceServer) GetRecommendUsers(ctx context.Context, req *pb.GetRecommendUsersReq) (*pb.GetRecommendUsersResp, error) {
	return logic.NewGetRecommendUsersLogic(ctx, s.svcCtx).GetRecommendUsers(req)
}
