// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: recommend.proto

package server

import (
	"context"

	"esx/app/recommend/rpc/internal/logic"
	"esx/app/recommend/rpc/internal/svc"
	"esx/app/recommend/rpc/xiaobaihe/recommend/pb"
)

type RecommendServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRecommendServiceServer
}

func NewRecommendServiceServer(svcCtx *svc.ServiceContext) *RecommendServiceServer {
	return &RecommendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendServiceServer) GetRecommendPosts(ctx context.Context, in *pb.GetRecommendPostsReq) (*pb.GetRecommendPostsResp, error) {
	l := logic.NewGetRecommendPostsLogic(ctx, s.svcCtx)
	return l.GetRecommendPosts(in)
}

func (s *RecommendServiceServer) GetSimilarPosts(ctx context.Context, in *pb.GetSimilarPostsReq) (*pb.GetSimilarPostsResp, error) {
	l := logic.NewGetSimilarPostsLogic(ctx, s.svcCtx)
	return l.GetSimilarPosts(in)
}

func (s *RecommendServiceServer) GetRecommendUsers(ctx context.Context, in *pb.GetRecommendUsersReq) (*pb.GetRecommendUsersResp, error) {
	l := logic.NewGetRecommendUsersLogic(ctx, s.svcCtx)
	return l.GetRecommendUsers(in)
}
