// Code generated by Kitex v0.16.2. DO NOT EDIT.

package interactionservice

import (
	"context"
	"errors"
	interaction "esx/kitex_gen/interaction"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Like": kitex.NewMethodInfo(
		likeHandler,
		newLikeArgs,
		newLikeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Unlike": kitex.NewMethodInfo(
		unlikeHandler,
		newUnlikeArgs,
		newUnlikeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CheckLiked": kitex.NewMethodInfo(
		checkLikedHandler,
		newCheckLikedArgs,
		newCheckLikedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchCheckLiked": kitex.NewMethodInfo(
		batchCheckLikedHandler,
		newBatchCheckLikedArgs,
		newBatchCheckLikedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Favorite": kitex.NewMethodInfo(
		favoriteHandler,
		newFavoriteArgs,
		newFavoriteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Unfavorite": kitex.NewMethodInfo(
		unfavoriteHandler,
		newUnfavoriteArgs,
		newUnfavoriteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"CheckFavorited": kitex.NewMethodInfo(
		checkFavoritedHandler,
		newCheckFavoritedArgs,
		newCheckFavoritedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"BatchCheckFavorited": kitex.NewMethodInfo(
		batchCheckFavoritedHandler,
		newBatchCheckFavoritedArgs,
		newBatchCheckFavoritedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetFavoriteList": kitex.NewMethodInfo(
		getFavoriteListHandler,
		newGetFavoriteListArgs,
		newGetFavoriteListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetLikeList": kitex.NewMethodInfo(
		getLikeListHandler,
		newGetLikeListArgs,
		newGetLikeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	interactionServiceServiceInfo                = NewServiceInfo()
	interactionServiceServiceInfoForClient       = NewServiceInfoForClient()
	interactionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interactionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interactionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InteractionService"
	handlerType := (*interaction.InteractionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interaction",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func likeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.LikeReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).Like(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *LikeArgs:
		success, err := handler.(interaction.InteractionService).Like(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LikeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newLikeArgs() interface{} {
	return &LikeArgs{}
}

func newLikeResult() interface{} {
	return &LikeResult{}
}

type LikeArgs struct {
	Req *interaction.LikeReq
}

func (p *LikeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *LikeArgs) Unmarshal(in []byte) error {
	msg := new(interaction.LikeReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LikeArgs_Req_DEFAULT *interaction.LikeReq

func (p *LikeArgs) GetReq() *interaction.LikeReq {
	if !p.IsSetReq() {
		return LikeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LikeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LikeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type LikeResult struct {
	Success *interaction.LikeResp
}

var LikeResult_Success_DEFAULT *interaction.LikeResp

func (p *LikeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *LikeResult) Unmarshal(in []byte) error {
	msg := new(interaction.LikeResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LikeResult) GetSuccess() *interaction.LikeResp {
	if !p.IsSetSuccess() {
		return LikeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LikeResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.LikeResp)
}

func (p *LikeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LikeResult) GetResult() interface{} {
	return p.Success
}

func unlikeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.UnlikeReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).Unlike(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnlikeArgs:
		success, err := handler.(interaction.InteractionService).Unlike(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnlikeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnlikeArgs() interface{} {
	return &UnlikeArgs{}
}

func newUnlikeResult() interface{} {
	return &UnlikeResult{}
}

type UnlikeArgs struct {
	Req *interaction.UnlikeReq
}

func (p *UnlikeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnlikeArgs) Unmarshal(in []byte) error {
	msg := new(interaction.UnlikeReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnlikeArgs_Req_DEFAULT *interaction.UnlikeReq

func (p *UnlikeArgs) GetReq() *interaction.UnlikeReq {
	if !p.IsSetReq() {
		return UnlikeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnlikeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnlikeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnlikeResult struct {
	Success *interaction.UnlikeResp
}

var UnlikeResult_Success_DEFAULT *interaction.UnlikeResp

func (p *UnlikeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnlikeResult) Unmarshal(in []byte) error {
	msg := new(interaction.UnlikeResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnlikeResult) GetSuccess() *interaction.UnlikeResp {
	if !p.IsSetSuccess() {
		return UnlikeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnlikeResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.UnlikeResp)
}

func (p *UnlikeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnlikeResult) GetResult() interface{} {
	return p.Success
}

func checkLikedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.CheckLikedReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).CheckLiked(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckLikedArgs:
		success, err := handler.(interaction.InteractionService).CheckLiked(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckLikedResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckLikedArgs() interface{} {
	return &CheckLikedArgs{}
}

func newCheckLikedResult() interface{} {
	return &CheckLikedResult{}
}

type CheckLikedArgs struct {
	Req *interaction.CheckLikedReq
}

func (p *CheckLikedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckLikedArgs) Unmarshal(in []byte) error {
	msg := new(interaction.CheckLikedReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckLikedArgs_Req_DEFAULT *interaction.CheckLikedReq

func (p *CheckLikedArgs) GetReq() *interaction.CheckLikedReq {
	if !p.IsSetReq() {
		return CheckLikedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckLikedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckLikedArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckLikedResult struct {
	Success *interaction.CheckLikedResp
}

var CheckLikedResult_Success_DEFAULT *interaction.CheckLikedResp

func (p *CheckLikedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckLikedResult) Unmarshal(in []byte) error {
	msg := new(interaction.CheckLikedResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckLikedResult) GetSuccess() *interaction.CheckLikedResp {
	if !p.IsSetSuccess() {
		return CheckLikedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckLikedResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.CheckLikedResp)
}

func (p *CheckLikedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckLikedResult) GetResult() interface{} {
	return p.Success
}

func batchCheckLikedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.BatchCheckLikedReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).BatchCheckLiked(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchCheckLikedArgs:
		success, err := handler.(interaction.InteractionService).BatchCheckLiked(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchCheckLikedResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchCheckLikedArgs() interface{} {
	return &BatchCheckLikedArgs{}
}

func newBatchCheckLikedResult() interface{} {
	return &BatchCheckLikedResult{}
}

type BatchCheckLikedArgs struct {
	Req *interaction.BatchCheckLikedReq
}

func (p *BatchCheckLikedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchCheckLikedArgs) Unmarshal(in []byte) error {
	msg := new(interaction.BatchCheckLikedReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchCheckLikedArgs_Req_DEFAULT *interaction.BatchCheckLikedReq

func (p *BatchCheckLikedArgs) GetReq() *interaction.BatchCheckLikedReq {
	if !p.IsSetReq() {
		return BatchCheckLikedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchCheckLikedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchCheckLikedArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchCheckLikedResult struct {
	Success *interaction.BatchCheckLikedResp
}

var BatchCheckLikedResult_Success_DEFAULT *interaction.BatchCheckLikedResp

func (p *BatchCheckLikedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchCheckLikedResult) Unmarshal(in []byte) error {
	msg := new(interaction.BatchCheckLikedResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchCheckLikedResult) GetSuccess() *interaction.BatchCheckLikedResp {
	if !p.IsSetSuccess() {
		return BatchCheckLikedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchCheckLikedResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.BatchCheckLikedResp)
}

func (p *BatchCheckLikedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchCheckLikedResult) GetResult() interface{} {
	return p.Success
}

func favoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.FavoriteReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).Favorite(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FavoriteArgs:
		success, err := handler.(interaction.InteractionService).Favorite(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FavoriteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFavoriteArgs() interface{} {
	return &FavoriteArgs{}
}

func newFavoriteResult() interface{} {
	return &FavoriteResult{}
}

type FavoriteArgs struct {
	Req *interaction.FavoriteReq
}

func (p *FavoriteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FavoriteArgs) Unmarshal(in []byte) error {
	msg := new(interaction.FavoriteReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FavoriteArgs_Req_DEFAULT *interaction.FavoriteReq

func (p *FavoriteArgs) GetReq() *interaction.FavoriteReq {
	if !p.IsSetReq() {
		return FavoriteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FavoriteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FavoriteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FavoriteResult struct {
	Success *interaction.FavoriteResp
}

var FavoriteResult_Success_DEFAULT *interaction.FavoriteResp

func (p *FavoriteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FavoriteResult) Unmarshal(in []byte) error {
	msg := new(interaction.FavoriteResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FavoriteResult) GetSuccess() *interaction.FavoriteResp {
	if !p.IsSetSuccess() {
		return FavoriteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FavoriteResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.FavoriteResp)
}

func (p *FavoriteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FavoriteResult) GetResult() interface{} {
	return p.Success
}

func unfavoriteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.UnfavoriteReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).Unfavorite(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *UnfavoriteArgs:
		success, err := handler.(interaction.InteractionService).Unfavorite(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*UnfavoriteResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newUnfavoriteArgs() interface{} {
	return &UnfavoriteArgs{}
}

func newUnfavoriteResult() interface{} {
	return &UnfavoriteResult{}
}

type UnfavoriteArgs struct {
	Req *interaction.UnfavoriteReq
}

func (p *UnfavoriteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UnfavoriteArgs) Unmarshal(in []byte) error {
	msg := new(interaction.UnfavoriteReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UnfavoriteArgs_Req_DEFAULT *interaction.UnfavoriteReq

func (p *UnfavoriteArgs) GetReq() *interaction.UnfavoriteReq {
	if !p.IsSetReq() {
		return UnfavoriteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UnfavoriteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UnfavoriteArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UnfavoriteResult struct {
	Success *interaction.UnfavoriteResp
}

var UnfavoriteResult_Success_DEFAULT *interaction.UnfavoriteResp

func (p *UnfavoriteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UnfavoriteResult) Unmarshal(in []byte) error {
	msg := new(interaction.UnfavoriteResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UnfavoriteResult) GetSuccess() *interaction.UnfavoriteResp {
	if !p.IsSetSuccess() {
		return UnfavoriteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UnfavoriteResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.UnfavoriteResp)
}

func (p *UnfavoriteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UnfavoriteResult) GetResult() interface{} {
	return p.Success
}

func checkFavoritedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.CheckFavoritedReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).CheckFavorited(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CheckFavoritedArgs:
		success, err := handler.(interaction.InteractionService).CheckFavorited(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CheckFavoritedResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCheckFavoritedArgs() interface{} {
	return &CheckFavoritedArgs{}
}

func newCheckFavoritedResult() interface{} {
	return &CheckFavoritedResult{}
}

type CheckFavoritedArgs struct {
	Req *interaction.CheckFavoritedReq
}

func (p *CheckFavoritedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CheckFavoritedArgs) Unmarshal(in []byte) error {
	msg := new(interaction.CheckFavoritedReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CheckFavoritedArgs_Req_DEFAULT *interaction.CheckFavoritedReq

func (p *CheckFavoritedArgs) GetReq() *interaction.CheckFavoritedReq {
	if !p.IsSetReq() {
		return CheckFavoritedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CheckFavoritedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CheckFavoritedArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CheckFavoritedResult struct {
	Success *interaction.CheckFavoritedResp
}

var CheckFavoritedResult_Success_DEFAULT *interaction.CheckFavoritedResp

func (p *CheckFavoritedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CheckFavoritedResult) Unmarshal(in []byte) error {
	msg := new(interaction.CheckFavoritedResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CheckFavoritedResult) GetSuccess() *interaction.CheckFavoritedResp {
	if !p.IsSetSuccess() {
		return CheckFavoritedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CheckFavoritedResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.CheckFavoritedResp)
}

func (p *CheckFavoritedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CheckFavoritedResult) GetResult() interface{} {
	return p.Success
}

func batchCheckFavoritedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.BatchCheckFavoritedReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).BatchCheckFavorited(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *BatchCheckFavoritedArgs:
		success, err := handler.(interaction.InteractionService).BatchCheckFavorited(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*BatchCheckFavoritedResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newBatchCheckFavoritedArgs() interface{} {
	return &BatchCheckFavoritedArgs{}
}

func newBatchCheckFavoritedResult() interface{} {
	return &BatchCheckFavoritedResult{}
}

type BatchCheckFavoritedArgs struct {
	Req *interaction.BatchCheckFavoritedReq
}

func (p *BatchCheckFavoritedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *BatchCheckFavoritedArgs) Unmarshal(in []byte) error {
	msg := new(interaction.BatchCheckFavoritedReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var BatchCheckFavoritedArgs_Req_DEFAULT *interaction.BatchCheckFavoritedReq

func (p *BatchCheckFavoritedArgs) GetReq() *interaction.BatchCheckFavoritedReq {
	if !p.IsSetReq() {
		return BatchCheckFavoritedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *BatchCheckFavoritedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *BatchCheckFavoritedArgs) GetFirstArgument() interface{} {
	return p.Req
}

type BatchCheckFavoritedResult struct {
	Success *interaction.BatchCheckFavoritedResp
}

var BatchCheckFavoritedResult_Success_DEFAULT *interaction.BatchCheckFavoritedResp

func (p *BatchCheckFavoritedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *BatchCheckFavoritedResult) Unmarshal(in []byte) error {
	msg := new(interaction.BatchCheckFavoritedResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *BatchCheckFavoritedResult) GetSuccess() *interaction.BatchCheckFavoritedResp {
	if !p.IsSetSuccess() {
		return BatchCheckFavoritedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *BatchCheckFavoritedResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.BatchCheckFavoritedResp)
}

func (p *BatchCheckFavoritedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *BatchCheckFavoritedResult) GetResult() interface{} {
	return p.Success
}

func getFavoriteListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.GetFavoriteListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).GetFavoriteList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFavoriteListArgs:
		success, err := handler.(interaction.InteractionService).GetFavoriteList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFavoriteListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFavoriteListArgs() interface{} {
	return &GetFavoriteListArgs{}
}

func newGetFavoriteListResult() interface{} {
	return &GetFavoriteListResult{}
}

type GetFavoriteListArgs struct {
	Req *interaction.GetFavoriteListReq
}

func (p *GetFavoriteListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFavoriteListArgs) Unmarshal(in []byte) error {
	msg := new(interaction.GetFavoriteListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFavoriteListArgs_Req_DEFAULT *interaction.GetFavoriteListReq

func (p *GetFavoriteListArgs) GetReq() *interaction.GetFavoriteListReq {
	if !p.IsSetReq() {
		return GetFavoriteListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFavoriteListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFavoriteListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFavoriteListResult struct {
	Success *interaction.GetFavoriteListResp
}

var GetFavoriteListResult_Success_DEFAULT *interaction.GetFavoriteListResp

func (p *GetFavoriteListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFavoriteListResult) Unmarshal(in []byte) error {
	msg := new(interaction.GetFavoriteListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFavoriteListResult) GetSuccess() *interaction.GetFavoriteListResp {
	if !p.IsSetSuccess() {
		return GetFavoriteListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFavoriteListResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.GetFavoriteListResp)
}

func (p *GetFavoriteListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFavoriteListResult) GetResult() interface{} {
	return p.Success
}

func getLikeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(interaction.GetLikeListReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(interaction.InteractionService).GetLikeList(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetLikeListArgs:
		success, err := handler.(interaction.InteractionService).GetLikeList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetLikeListResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetLikeListArgs() interface{} {
	return &GetLikeListArgs{}
}

func newGetLikeListResult() interface{} {
	return &GetLikeListResult{}
}

type GetLikeListArgs struct {
	Req *interaction.GetLikeListReq
}

func (p *GetLikeListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetLikeListArgs) Unmarshal(in []byte) error {
	msg := new(interaction.GetLikeListReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetLikeListArgs_Req_DEFAULT *interaction.GetLikeListReq

func (p *GetLikeListArgs) GetReq() *interaction.GetLikeListReq {
	if !p.IsSetReq() {
		return GetLikeListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetLikeListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetLikeListArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetLikeListResult struct {
	Success *interaction.GetLikeListResp
}

var GetLikeListResult_Success_DEFAULT *interaction.GetLikeListResp

func (p *GetLikeListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetLikeListResult) Unmarshal(in []byte) error {
	msg := new(interaction.GetLikeListResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetLikeListResult) GetSuccess() *interaction.GetLikeListResp {
	if !p.IsSetSuccess() {
		return GetLikeListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetLikeListResult) SetSuccess(x interface{}) {
	p.Success = x.(*interaction.GetLikeListResp)
}

func (p *GetLikeListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetLikeListResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Like(ctx context.Context, Req *interaction.LikeReq) (r *interaction.LikeResp, err error) {
	var _args LikeArgs
	_args.Req = Req
	var _result LikeResult
	if err = p.c.Call(ctx, "Like", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Unlike(ctx context.Context, Req *interaction.UnlikeReq) (r *interaction.UnlikeResp, err error) {
	var _args UnlikeArgs
	_args.Req = Req
	var _result UnlikeResult
	if err = p.c.Call(ctx, "Unlike", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckLiked(ctx context.Context, Req *interaction.CheckLikedReq) (r *interaction.CheckLikedResp, err error) {
	var _args CheckLikedArgs
	_args.Req = Req
	var _result CheckLikedResult
	if err = p.c.Call(ctx, "CheckLiked", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchCheckLiked(ctx context.Context, Req *interaction.BatchCheckLikedReq) (r *interaction.BatchCheckLikedResp, err error) {
	var _args BatchCheckLikedArgs
	_args.Req = Req
	var _result BatchCheckLikedResult
	if err = p.c.Call(ctx, "BatchCheckLiked", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Favorite(ctx context.Context, Req *interaction.FavoriteReq) (r *interaction.FavoriteResp, err error) {
	var _args FavoriteArgs
	_args.Req = Req
	var _result FavoriteResult
	if err = p.c.Call(ctx, "Favorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Unfavorite(ctx context.Context, Req *interaction.UnfavoriteReq) (r *interaction.UnfavoriteResp, err error) {
	var _args UnfavoriteArgs
	_args.Req = Req
	var _result UnfavoriteResult
	if err = p.c.Call(ctx, "Unfavorite", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckFavorited(ctx context.Context, Req *interaction.CheckFavoritedReq) (r *interaction.CheckFavoritedResp, err error) {
	var _args CheckFavoritedArgs
	_args.Req = Req
	var _result CheckFavoritedResult
	if err = p.c.Call(ctx, "CheckFavorited", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchCheckFavorited(ctx context.Context, Req *interaction.BatchCheckFavoritedReq) (r *interaction.BatchCheckFavoritedResp, err error) {
	var _args BatchCheckFavoritedArgs
	_args.Req = Req
	var _result BatchCheckFavoritedResult
	if err = p.c.Call(ctx, "BatchCheckFavorited", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFavoriteList(ctx context.Context, Req *interaction.GetFavoriteListReq) (r *interaction.GetFavoriteListResp, err error) {
	var _args GetFavoriteListArgs
	_args.Req = Req
	var _result GetFavoriteListResult
	if err = p.c.Call(ctx, "GetFavoriteList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLikeList(ctx context.Context, Req *interaction.GetLikeListReq) (r *interaction.GetLikeListResp, err error) {
	var _args GetLikeListArgs
	_args.Req = Req
	var _result GetLikeListResult
	if err = p.c.Call(ctx, "GetLikeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
