// Code generated by scripts/generate_rpc_adapters.py. DO NOT EDIT.

package behaviorservice

import (
	"context"
	pb "esx/kitex_gen/behavior"
	native "esx/kitex_gen/behavior/behaviorservice"
	"esx/pkg/rpcx"
	"github.com/cloudwego/kitex/client/callopt"
	"io"
)

type ClientBehaviorEvent = pb.ClientBehaviorEvent
type RecordEventsReq = pb.RecordEventsReq
type RecordEventResult = pb.RecordEventResult
type RecordEventsResp = pb.RecordEventsResp
type BehaviorService = native.Client
type client struct{ native.Client }

func NewBehaviorService(spec rpcx.Client) BehaviorService {
	raw := native.MustNewClient(spec.ServiceName(), spec.Options()...)
	spec.Track(raw.(io.Closer))
	return &client{Client: raw}
}
func (c *client) RecordEvents(ctx context.Context, req *pb.RecordEventsReq, opts ...callopt.Option) (*pb.RecordEventsResp, error) {
	v, e := c.Client.RecordEvents(ctx, req, opts...)
	return v, rpcx.FromTransportError(e)
}
