// Code generated by scripts/generate_rpc_adapters.py. DO NOT EDIT.

package feedservice

import (
	"context"
	pb "esx/kitex_gen/feed"
	native "esx/kitex_gen/feed/feedservice"
	"esx/pkg/rpcx"
	"github.com/cloudwego/kitex/client/callopt"
	"io"
)

type FeedItem = pb.FeedItem
type GetFollowFeedReq = pb.GetFollowFeedReq
type GetFollowFeedResp = pb.GetFollowFeedResp
type GetRecommendFeedReq = pb.GetRecommendFeedReq
type GetRecommendFeedResp = pb.GetRecommendFeedResp
type PushToInboxReq = pb.PushToInboxReq
type PushToInboxResp = pb.PushToInboxResp
type FanoutPostReq = pb.FanoutPostReq
type FanoutPostResp = pb.FanoutPostResp
type FeedService = native.Client
type client struct{ native.Client }

func NewFeedService(spec rpcx.Client) FeedService {
	raw := native.MustNewClient(spec.ServiceName(), spec.Options()...)
	spec.Track(raw.(io.Closer))
	return &client{Client: raw}
}
func (c *client) GetFollowFeed(ctx context.Context, req *pb.GetFollowFeedReq, opts ...callopt.Option) (*pb.GetFollowFeedResp, error) {
	v, e := c.Client.GetFollowFeed(ctx, req, opts...)
	return v, rpcx.FromTransportError(e)
}
func (c *client) GetRecommendFeed(ctx context.Context, req *pb.GetRecommendFeedReq, opts ...callopt.Option) (*pb.GetRecommendFeedResp, error) {
	v, e := c.Client.GetRecommendFeed(ctx, req, opts...)
	return v, rpcx.FromTransportError(e)
}
func (c *client) PushToInbox(ctx context.Context, req *pb.PushToInboxReq, opts ...callopt.Option) (*pb.PushToInboxResp, error) {
	v, e := c.Client.PushToInbox(ctx, req, opts...)
	return v, rpcx.FromTransportError(e)
}
func (c *client) FanoutPost(ctx context.Context, req *pb.FanoutPostReq, opts ...callopt.Option) (*pb.FanoutPostResp, error) {
	v, e := c.Client.FanoutPost(ctx, req, opts...)
	return v, rpcx.FromTransportError(e)
}
