// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/inference/inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Features      map[string]float64     `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	CoarseScore   float64                `protobuf:"fixed64,3,opt,name=coarse_score,json=coarseScore,proto3" json:"coarse_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankCandidate) Reset() {
	*x = RankCandidate{}
	mi := &file_proto_inference_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankCandidate) ProtoMessage() {}

func (x *RankCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankCandidate.ProtoReflect.Descriptor instead.
func (*RankCandidate) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{0}
}

func (x *RankCandidate) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *RankCandidate) GetFeatures() map[string]float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *RankCandidate) GetCoarseScore() float64 {
	if x != nil {
		return x.CoarseScore
	}
	return 0
}

type RankReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Candidates    []*RankCandidate       `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankReq) Reset() {
	*x = RankReq{}
	mi := &file_proto_inference_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankReq) ProtoMessage() {}

func (x *RankReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankReq.ProtoReflect.Descriptor instead.
func (*RankReq) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{1}
}

func (x *RankReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RankReq) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *RankReq) GetCandidates() []*RankCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type RankedCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedCandidate) Reset() {
	*x = RankedCandidate{}
	mi := &file_proto_inference_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedCandidate) ProtoMessage() {}

func (x *RankedCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedCandidate.ProtoReflect.Descriptor instead.
func (*RankedCandidate) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{2}
}

func (x *RankedCandidate) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *RankedCandidate) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RankResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*RankedCandidate     `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankResp) Reset() {
	*x = RankResp{}
	mi := &file_proto_inference_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankResp) ProtoMessage() {}

func (x *RankResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankResp.ProtoReflect.Descriptor instead.
func (*RankResp) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{3}
}

func (x *RankResp) GetCandidates() []*RankedCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *RankResp) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type ReloadModelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelVersion  string                 `protobuf:"bytes,1,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ModelUri      string                 `protobuf:"bytes,2,opt,name=model_uri,json=modelUri,proto3" json:"model_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadModelReq) Reset() {
	*x = ReloadModelReq{}
	mi := &file_proto_inference_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadModelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadModelReq) ProtoMessage() {}

func (x *ReloadModelReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadModelReq.ProtoReflect.Descriptor instead.
func (*ReloadModelReq) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadModelReq) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *ReloadModelReq) GetModelUri() string {
	if x != nil {
		return x.ModelUri
	}
	return ""
}

type ReloadModelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        bool                   `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadModelResp) Reset() {
	*x = ReloadModelResp{}
	mi := &file_proto_inference_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadModelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadModelResp) ProtoMessage() {}

func (x *ReloadModelResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadModelResp.ProtoReflect.Descriptor instead.
func (*ReloadModelResp) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadModelResp) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *ReloadModelResp) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type InferHealthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferHealthReq) Reset() {
	*x = InferHealthReq{}
	mi := &file_proto_inference_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferHealthReq) ProtoMessage() {}

func (x *InferHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferHealthReq.ProtoReflect.Descriptor instead.
func (*InferHealthReq) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{6}
}

type InferHealthResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ready          bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	LoadedVersions []string               `protobuf:"bytes,2,rep,name=loaded_versions,json=loadedVersions,proto3" json:"loaded_versions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InferHealthResp) Reset() {
	*x = InferHealthResp{}
	mi := &file_proto_inference_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferHealthResp) ProtoMessage() {}

func (x *InferHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inference_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferHealthResp.ProtoReflect.Descriptor instead.
func (*InferHealthResp) Descriptor() ([]byte, []int) {
	return file_proto_inference_inference_proto_rawDescGZIP(), []int{7}
}

func (x *InferHealthResp) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *InferHealthResp) GetLoadedVersions() []string {
	if x != nil {
		return x.LoadedVersions
	}
	return nil
}

var File_proto_inference_inference_proto protoreflect.FileDescriptor

const file_proto_inference_inference_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/inference/inference.proto\x12\tinference\"\xcc\x01\n" +
	"\rRankCandidate\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12B\n" +
	"\bfeatures\x18\x02 \x03(\v2&.inference.RankCandidate.FeaturesEntryR\bfeatures\x12!\n" +
	"\fcoarse_score\x18\x03 \x01(\x01R\vcoarseScore\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x87\x01\n" +
	"\aRankReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\x128\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x18.inference.RankCandidateR\n" +
	"candidates\"@\n" +
	"\x0fRankedCandidate\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"k\n" +
	"\bRankResp\x12:\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1a.inference.RankedCandidateR\n" +
	"candidates\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\"R\n" +
	"\x0eReloadModelReq\x12#\n" +
	"\rmodel_version\x18\x01 \x01(\tR\fmodelVersion\x12\x1b\n" +
	"\tmodel_uri\x18\x02 \x01(\tR\bmodelUri\"N\n" +
	"\x0fReloadModelResp\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\bR\x06loaded\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\"\x10\n" +
	"\x0eInferHealthReq\"P\n" +
	"\x0fInferHealthResp\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12'\n" +
	"\x0floaded_versions\x18\x02 \x03(\tR\x0eloadedVersions2\xcc\x01\n" +
	"\x12OnlineInferService\x12/\n" +
	"\x04Rank\x12\x12.inference.RankReq\x1a\x13.inference.RankResp\x12D\n" +
	"\vReloadModel\x12\x19.inference.ReloadModelReq\x1a\x1a.inference.ReloadModelResp\x12?\n" +
	"\x06Health\x12\x19.inference.InferHealthReq\x1a\x1a.inference.InferHealthRespB\x18Z\x16xiaobaihe/inference/pbb\x06proto3"

var (
	file_proto_inference_inference_proto_rawDescOnce sync.Once
	file_proto_inference_inference_proto_rawDescData []byte
)

func file_proto_inference_inference_proto_rawDescGZIP() []byte {
	file_proto_inference_inference_proto_rawDescOnce.Do(func() {
		file_proto_inference_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inference_inference_proto_rawDesc), len(file_proto_inference_inference_proto_rawDesc)))
	})
	return file_proto_inference_inference_proto_rawDescData
}

var file_proto_inference_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_inference_inference_proto_goTypes = []any{
	(*RankCandidate)(nil),   // 0: inference.RankCandidate
	(*RankReq)(nil),         // 1: inference.RankReq
	(*RankedCandidate)(nil), // 2: inference.RankedCandidate
	(*RankResp)(nil),        // 3: inference.RankResp
	(*ReloadModelReq)(nil),  // 4: inference.ReloadModelReq
	(*ReloadModelResp)(nil), // 5: inference.ReloadModelResp
	(*InferHealthReq)(nil),  // 6: inference.InferHealthReq
	(*InferHealthResp)(nil), // 7: inference.InferHealthResp
	nil,                     // 8: inference.RankCandidate.FeaturesEntry
}
var file_proto_inference_inference_proto_depIdxs = []int32{
	8, // 0: inference.RankCandidate.features:type_name -> inference.RankCandidate.FeaturesEntry
	0, // 1: inference.RankReq.candidates:type_name -> inference.RankCandidate
	2, // 2: inference.RankResp.candidates:type_name -> inference.RankedCandidate
	1, // 3: inference.OnlineInferService.Rank:input_type -> inference.RankReq
	4, // 4: inference.OnlineInferService.ReloadModel:input_type -> inference.ReloadModelReq
	6, // 5: inference.OnlineInferService.Health:input_type -> inference.InferHealthReq
	3, // 6: inference.OnlineInferService.Rank:output_type -> inference.RankResp
	5, // 7: inference.OnlineInferService.ReloadModel:output_type -> inference.ReloadModelResp
	7, // 8: inference.OnlineInferService.Health:output_type -> inference.InferHealthResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inference_inference_proto_init() }
func file_proto_inference_inference_proto_init() {
	if File_proto_inference_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inference_inference_proto_rawDesc), len(file_proto_inference_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inference_inference_proto_goTypes,
		DependencyIndexes: file_proto_inference_inference_proto_depIdxs,
		MessageInfos:      file_proto_inference_inference_proto_msgTypes,
	}.Build()
	File_proto_inference_inference_proto = out.File
	file_proto_inference_inference_proto_goTypes = nil
	file_proto_inference_inference_proto_depIdxs = nil
}
