// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RecordBehaviorEventsReq struct {
	AnonymousId string          `json:"anonymousId,optional"`
	SessionId   string          `json:"sessionId,optional"`
	Events      []BehaviorEvent `json:"events"`
}

type RecordBehaviorEventsResp struct {
	Results       []BehaviorEventResult `json:"results"`
	AcceptedCount int32                 `json:"acceptedCount"`
	RejectedCount int32                 `json:"rejectedCount"`
}
