// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginReq struct {
	Username   string `json:"username,optional"`
	Password   string `json:"password,optional"`
	Phone      string `json:"phone,optional"`
	VerifyCode string `json:"verifyCode,optional"`
	LoginType  int32  `json:"loginType"` // 1:密码登录 2:验证码登录
}

type LoginResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Phone      string `json:"phone,optional"`
	VerifyCode string `json:"verifyCode,optional"`
}

type RegisterResp struct {
	UserId int64  `json:"userId"`
	Token  string `json:"token"`
}

type SendVerifyCodeReq struct {
	Phone string `json:"phone"`
	Type  int32  `json:"type"` // 1:注册 2:登录 3:重置密码
}

type SendVerifyCodeResp struct {
}
