// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreatePostReq struct {
	Title          string   `json:"title"`
	Content        string   `json:"content"`
	Images         []string `json:"images,optional"`
	Tags           []string `json:"tags,optional"`
	Status         int32    `json:"status,optional"` // 0:草稿 1:发布
	IdempotencyKey string   `json:"idempotencyKey,optional"`
	MediaIds       []int64  `json:"mediaIds,optional"`
}

type CreatePostResp struct {
	PostId   int64 `json:"postId"`
	Status   int32 `json:"status"`
	Revision int64 `json:"revision"`
}

type DeletePostReq struct {
	PostId           int64 `path:"postId"`
	ExpectedRevision int64 `json:"expectedRevision,optional"` // 迁移期可选；提供时做版本冲突检测
}

type DeletePostResp struct {
}

type GetPostListReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"pageSize,default=20"`
	SortBy   int32 `form:"sortBy,default=1"` // 1:最新 2:热门 3:推荐
}

type GetPostReq struct {
	PostId int64 `path:"postId"`
}

type GetPostResp struct {
	Id            int64    `json:"id"`
	AuthorId      int64    `json:"authorId"`
	AuthorName    string   `json:"authorName"`
	AuthorAvatar  string   `json:"authorAvatar"`
	Title         string   `json:"title"`
	Content       string   `json:"content"`
	Images        []string `json:"images"`
	Tags          []string `json:"tags"`
	Status        int32    `json:"status"`
	ViewCount     int64    `json:"viewCount"`
	LikeCount     int64    `json:"likeCount"`
	CommentCount  int64    `json:"commentCount"`
	FavoriteCount int64    `json:"favoriteCount"`
	IsLiked       bool     `json:"isLiked"`
	IsFavorited   bool     `json:"isFavorited"`
	Revision      int64    `json:"revision"`
	CreatedAt     int64    `json:"createdAt"`
}

type UpdatePostReq struct {
	PostId           int64    `path:"postId"`
	Title            string   `json:"title,optional"`
	Content          string   `json:"content,optional"`
	Images           []string `json:"images,optional"`
	Tags             []string `json:"tags,optional"`
	Status           *int32   `json:"status,optional"`           // 显式状态变更；0:草稿 1:发布
	ExpectedRevision int64    `json:"expectedRevision,optional"` // 迁移期可选；提供时做版本冲突检测
	MediaIds         []int64  `json:"mediaIds,optional"`
}

type UpdatePostResp struct {
	Status   int32 `json:"status"`
	Revision int64 `json:"revision"`
}
