// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type SearchReq struct {
	Keyword  string `form:"keyword"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=20"`
}

type SearchResp struct {
	Posts            []SearchPostItem `json:"posts"`
	Users            []SearchUserItem `json:"users"`
	Tags             []SearchTagItem  `json:"tags"`
	Degraded         bool             `json:"degraded"`
	UnavailableTypes []string         `json:"unavailableTypes,optional"`
}

type SearchTagsReq struct {
	Keyword string `form:"keyword"`
	Limit   int32  `form:"limit,default=20"`
}

type SearchTagsResp struct {
	Tags []SearchTagItem `json:"tags"`
}

type SearchUsersReq struct {
	Keyword  string `form:"keyword"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"pageSize,default=20"`
}

type SearchUsersResp struct {
	Users []SearchUserItem `json:"users"`
	Total int64            `json:"total"`
}
