// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CommentItem struct {
	Id          int64  `json:"id"`
	UserId      int64  `json:"userId"`
	UserName    string `json:"userName"`
	UserAvatar  string `json:"userAvatar"`
	ParentId    int64  `json:"parentId"`
	ReplyUserId int64  `json:"replyUserId"`
	Content     string `json:"content"`
	LikeCount   int64  `json:"likeCount"`
	CreatedAt   int64  `json:"createdAt"`
}

type HealthReq struct {
}

type HealthResp struct {
	Status string `json:"status"`
}

type PostItem struct {
	Id           int64    `json:"id"`
	AuthorId     int64    `json:"authorId"`
	AuthorName   string   `json:"authorName"`
	AuthorAvatar string   `json:"authorAvatar"`
	Title        string   `json:"title"`
	Content      string   `json:"content"`
	Images       []string `json:"images"`
	Tags         []string `json:"tags"`
	ViewCount    int64    `json:"viewCount"`
	LikeCount    int64    `json:"likeCount"`
	CommentCount int64    `json:"commentCount"`
	CreatedAt    int64    `json:"createdAt"`
}
